# Character-Level LSTM in PyTorch

In this notebook, I'll construct a character-level LSTM with PyTorch. The network will train character by character on some text, then generate new text character by character. As an example, I will train on Anna Karenina. **This model will be able to generate new text based on the text from the book!**

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

First let's load in our required resources for data loading and model creation.

In [1]:
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F

## Load in Data

Then, we'll load the Anna Karenina text file and convert it into integers for our network to use. 

In [2]:
# open text file and read in data as `text`
with open('data/anna.txt', 'r') as f:
    text = f.read()

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [3]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

### Tokenization

In the cells, below, I'm creating a couple **dictionaries** to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [4]:
# encode the text and map each character to an integer and vice versa

# we create two dictionaries:
# 1. int2char, which maps integers to characters
# 2. char2int, which maps characters to unique integers
chars = tuple(set(text))
int2char = dict(enumerate(chars))
char2int = {ch: ii for ii, ch in int2char.items()}

# encode the text
encoded = np.array([char2int[ch] for ch in text])

And we can see those same characters from above, encoded as integers.

In [5]:
encoded[:100]

array([ 2, 73, 18, 21, 48, 81, 63, 42, 15,  6,  6,  6,  5, 18, 21, 21, 43,
       42, 75, 18,  1, 67, 53, 67, 81, 70, 42, 18, 63, 81, 42, 18, 53, 53,
       42, 18, 53, 67, 37, 81, 52, 42, 81, 47, 81, 63, 43, 42, 60, 49, 73,
       18, 21, 21, 43, 42, 75, 18,  1, 67, 53, 43, 42, 67, 70, 42, 60, 49,
       73, 18, 21, 21, 43, 42, 67, 49, 42, 67, 48, 70, 42, 36, 62, 49,  6,
       62, 18, 43, 14,  6,  6, 30, 47, 81, 63, 43, 48, 73, 67, 49])

## Pre-processing the data

As you can see in our char-RNN image above, our LSTM expects an input that is **one-hot encoded** meaning that each character is converted into an integer (via our created dictionary) and *then* converted into a column vector where only it's corresponding integer index will have the value of 1 and the rest of the vector will be filled with 0's. Since we're one-hot encoding the data, let's make a function to do that!


In [12]:
def one_hot_encode(arr, n_labels):
    
    # Initialize the the encoded array
    one_hot = np.zeros((arr.size, n_labels), dtype=np.float32)
    
    # Fill the appropriate elements with ones
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.
    
    # Finally reshape it to get back to the original array
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    
    return one_hot

In [13]:
# check that the function works as expected
test_seq = np.array([[3, 5, 1]])
one_hot = one_hot_encode(test_seq, 8)

print(one_hot)

[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]]


## Making training mini-batches


To train on this data, we also want to create mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>

In this example, we'll take the encoded characters (passed in as the `arr` parameter) and split them into multiple sequences, given by `batch_size`. Each of our sequences will be `seq_length` long.

### Creating Batches

**1. The first thing we need to do is discard some of the text so we only have completely full mini-batches. **

Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences in a batch) and $M$ is the seq_length or number of time steps in a sequence. Then, to get the total number of batches, $K$, that we can make from the array `arr`, you divide the length of `arr` by the number of characters per batch. Once you know the number of batches, you can get the total number of characters to keep from `arr`, $N * M * K$.

**2. After that, we need to split `arr` into $N$ batches. ** 

You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences in a batch, so let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$.

**3. Now that we have this array, we can iterate through it to get our mini-batches. **

The idea is each batch is a $N \times M$ window on the $N \times (M * K)$ array. For each subsequent batch, the window moves over by `seq_length`. We also want to create both the input and target arrays. Remember that the targets are just the inputs shifted over by one character. The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of tokens in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `seq_length` wide.

> **TODO:** Write the code for creating batches in the function below. The exercises in this notebook _will not be easy_. I've provided a notebook with solutions alongside this notebook. If you get stuck, checkout the solutions. The most important thing is that you don't copy and paste the code into here, **type out the solution code yourself.**

In [153]:
def get_batches(arr, batch_size, seq_length):
    '''Create a generator that returns batches of size
       batch_size x seq_length from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       batch_size: Batch size, the number of sequences per batch
       seq_length: Number of encoded chars in a sequence
    '''    
    ## TODO: Get the number of batches we can make
    single_batch_length = batch_size * seq_length
    n_batches = len(arr) // single_batch_length
    total_length = len(arr) - (len(arr) % single_batch_length)
    
    ## TODO: Keep only enough characters to make full batches
    arr = arr[:total_length]
    
    ## TODO: Reshape into batch_size rows
    # This will create batch_size rows, each row will be total_length / batch_size in length
    # and each row will include (total_length / batch_size) / seq_length sequences, each of length seq_length.
    # You can change the shape of this arr if you want, but that will mean you will need to construct batches differently
    # in the subsequent for loop.
    arr = arr.reshape((batch_size, -1))
    
    ## TODO: Iterate over the batches using a window of size seq_length
    for n in range(0, arr.shape[1], seq_length):
        # The features
#         x = arr[:, n: n + seq_length]
#         # The targets, shifted by one
#         y = arr[:, n + 1: n + 1 + seq_length]
#         yield x, y

        x = arr[:, n:n+seq_length]
        # The targets, shifted by one
        y = np.zeros_like(x)
        try:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, n+seq_length]
        except IndexError:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, 0]
        yield x, y

### Test Your Implementation

Now I'll make some data sets and we can check out what's going on as we batch data. Here, as an example, I'm going to use a batch size of 8 and 50 sequence steps.

In [154]:
batches = get_batches(encoded, 8, 50)
x, y = next(batches)

In [155]:
# printing out the first 10 items in a sequence
# Should produce 8 rows and the first 10 items of the first 50-long sequence as columns.
print('x\n', x[:10, :10])
# x shifted by 1
print('\ny\n', y[:10, :10])

x
 [[ 2 73 18 21 48 81 63 42 15  6]
 [70 36 49 42 48 73 18 48 42 18]
 [81 49 55 42 36 63 42 18 42 75]
 [70 42 48 73 81 42 82 73 67 81]
 [42 70 18 62 42 73 81 63 42 48]
 [82 60 70 70 67 36 49 42 18 49]
 [42 31 49 49 18 42 73 18 55 42]
 [28 65 53 36 49 70 37 43 14 42]]

y
 [[73 18 21 48 81 63 42 15  6  6]
 [36 49 42 48 73 18 48 42 18 48]
 [49 55 42 36 63 42 18 42 75 36]
 [42 48 73 81 42 82 73 67 81 75]
 [70 18 62 42 73 81 63 42 48 81]
 [60 70 70 67 36 49 42 18 49 55]
 [31 49 49 18 42 73 18 55 42 70]
 [65 53 36 49 70 37 43 14 42 79]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[25  8 60 11 45 27 28 73  1  2]
 [17  7 20 73 45  8 60 45 73 60]
 [27 20 80 73  7 28 73 60 73 65]
 [17 73 45  8 27 73 66  8 46 27]
 [73 17 60 12 73  8 27 28 73 45]
 [66 64 17 17 46  7 20 73 60 20]
 [73 76 20 20 60 73  8 60 80 73]
 [47 35 43  7 20 17 24 50 37 73]]

y
 [[ 8 60 11 45 27 28 73  1  2  2]
 [ 7 20 73 45  8 60 45 73 60 45]
 [20 80 73  7 28 73 60 73 65  7]
 [73 45  8 27 73 66  8 46 27 65]
 [17 60 12 73  8 27 28 73 45 27]
 [64 17 17 46  7 20 73 60 20 80]
 [76 20 20 60 73  8 60 80 73 17]
 [35 43  7 20 17 24 50 37 73 36]]
 ```
 although the exact numbers may be different. Check to make sure the data is shifted over one step for `y`.

---
## Defining the network with PyTorch

Below is where you'll define the network.

<img src="assets/charRNN.png" width=500px>

Next, you'll use PyTorch to define the architecture of the network. We start by defining the layers and operations we want. Then, define a method for the forward pass. You've also been given a method for predicting characters.

### Model Structure

In `__init__` the suggested structure is as follows:
* Create and store the necessary dictionaries (this has been done for you)
* Define an LSTM layer that takes as params: an input size (the number of characters), a hidden layer size `n_hidden`, a number of layers `n_layers`, a dropout probability `drop_prob`, and a batch_first boolean (True, since we are batching)
* Define a dropout layer with `drop_prob`
* Define a fully-connected layer with params: input size `n_hidden` and output size (the number of characters)
* Finally, initialize the weights (again, this has been given)

Note that some parameters have been named and given in the `__init__` function, and we use them and store them by doing something like `self.drop_prob = drop_prob`.

---
### LSTM Inputs/Outputs

You can create a basic [LSTM layer](https://pytorch.org/docs/stable/nn.html#lstm) as follows

```python
self.lstm = nn.LSTM(input_size, n_hidden, n_layers, 
                            dropout=drop_prob, batch_first=True)
```

where `input_size` is the number of characters this cell expects to see as sequential input, and `n_hidden` is the number of units in the hidden layers in the cell. And we can add dropout by adding a dropout parameter with a specified probability; this will automatically add dropout to the inputs or outputs. Finally, in the `forward` function, we can stack up the LSTM cells into layers using `.view`. With this, you pass in a list of cells and it will send the output of one cell into the next cell.

We also need to create an initial hidden state of all zeros. This is done like so

```python
self.init_hidden()
```

In [156]:
# check if GPU is available
train_on_gpu = torch.cuda.is_available()
if(train_on_gpu):
    print('Training on GPU!')
else: 
    print('No GPU available, training on CPU; consider making n_epochs very small.')

No GPU available, training on CPU; consider making n_epochs very small.


In [157]:
class CharRNN(nn.Module):
    
    def __init__(self, tokens, n_hidden=256, n_layers=2,
                               drop_prob=0.5, lr=0.001):
        super().__init__()
        self.drop_prob = drop_prob
        self.n_layers = n_layers
        self.n_hidden = n_hidden
        self.lr = lr
        
        # creating character dictionaries
        self.chars = tokens
        self.int2char = dict(enumerate(self.chars))
        self.char2int = {ch: ii for ii, ch in self.int2char.items()}
        
        ## TODO: define the layers of the model
        self.lstm = nn.LSTM(input_size=len(tokens), hidden_size=n_hidden, num_layers=n_layers,
                            dropout=drop_prob, batch_first=True)
        
        ## TODO: define a dropout layer
        self.dropout = nn.Dropout(drop_prob)
        self.fc = nn.Linear(n_hidden, len(tokens))
      
    
    def forward(self, x, hidden):
        ''' Forward pass through the network. 
            These inputs are x, and the hidden/cell state `hidden`. '''
                
        ## TODO: Get the outputs and the new hidden state from the lstm
        r_output, hidden = self.lstm(x, hidden)
        out = self.dropout(r_output)
        # Stack up LSTM outputs using view
        # you may need to use contiguous to reshape the output
        out = out.contiguous().view(-1, self.n_hidden)
        out = self.fc(out)
        
        # return the final output and the hidden state
        return out, hidden
    
    
    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x n_hidden,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        
        if (train_on_gpu):
            hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.n_hidden).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_(),
                      weight.new(self.n_layers, batch_size, self.n_hidden).zero_())
        
        return hidden
        

## Time to train

The train function gives us the ability to set the number of epochs, the learning rate, and other parameters.

Below we're using an Adam optimizer and cross entropy loss since we are looking at character class scores as output. We calculate the loss and perform backpropagation, as usual!

A couple of details about training: 
>* Within the batch loop, we detach the hidden state from its history; this time setting it equal to a new *tuple* variable because an LSTM has a hidden state that is a tuple of the hidden and cell states.
* We use [`clip_grad_norm_`](https://pytorch.org/docs/stable/_modules/torch/nn/utils/clip_grad.html) to help prevent exploding gradients.

In [158]:
def train(net, data, epochs=10, batch_size=10, seq_length=50, lr=0.001, clip=5, val_frac=0.1, print_every=10):
    ''' Training a network 
    
        Arguments
        ---------
        
        net: CharRNN network
        data: text data to train the network
        epochs: Number of epochs to train
        batch_size: Number of mini-sequences per mini-batch, aka batch size
        seq_length: Number of character steps per mini-batch
        lr: learning rate
        clip: gradient clipping
        val_frac: Fraction of data to hold out for validation
        print_every: Number of steps for printing training and validation loss
    
    '''
    net.train()
    
    opt = torch.optim.Adam(net.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    
    # create training and validation data
    val_idx = int(len(data)*(1-val_frac))
    data, val_data = data[:val_idx], data[val_idx:]
    
    if(train_on_gpu):
        net.cuda()
    
    counter = 0
    n_chars = len(net.chars)
    for e in range(epochs):
        # initialize hidden state
        h = net.init_hidden(batch_size)
        
        for x, y in get_batches(data, batch_size, seq_length):
            counter += 1
            
            # One-hot encode our data and make them Torch tensors
            x = one_hot_encode(x, n_chars)
            inputs, targets = torch.from_numpy(x), torch.from_numpy(y)
            
            if(train_on_gpu):
                inputs, targets = inputs.cuda(), targets.cuda()

            # Creating new variables for the hidden state, otherwise
            # we'd backprop through the entire training history
            h = tuple([each.data for each in h])

            # zero accumulated gradients
            net.zero_grad()
            
            # get the output from the model
            output, h = net(inputs, h)
            
            # calculate the loss and perform backprop
            loss = criterion(output, targets.contiguous().view(batch_size*seq_length).long())
            loss.backward()
            # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
            nn.utils.clip_grad_norm_(net.parameters(), clip)
            opt.step()
            
            # loss stats
            if counter % print_every == 0:
                # Get validation loss
                val_h = net.init_hidden(batch_size)
                val_losses = []
                net.eval()
                for x, y in get_batches(val_data, batch_size, seq_length):
                    # One-hot encode our data and make them Torch tensors
                    x = one_hot_encode(x, n_chars)
                    x, y = torch.from_numpy(x), torch.from_numpy(y)
                    
                    # Creating new variables for the hidden state, otherwise
                    # we'd backprop through the entire training history
                    val_h = tuple([each.data for each in val_h])
                    
                    inputs, targets = x, y
                    if(train_on_gpu):
                        inputs, targets = inputs.cuda(), targets.cuda()

                    output, val_h = net(inputs, val_h)
                    val_loss = criterion(output, targets.contiguous().view(batch_size*seq_length).long())
                
                    val_losses.append(val_loss.item())
                
                net.train() # reset to train mode after iterationg through validation data
                
                print("Epoch: {}/{}...".format(e+1, epochs),
                      "Step: {}...".format(counter),
                      "Loss: {:.4f}...".format(loss.item()),
                      "Val Loss: {:.4f}".format(np.mean(val_losses)))

## Instantiating the model

Now we can actually train the network. First we'll create the network itself, with some given hyperparameters. Then, define the mini-batches sizes, and start training!

In [159]:
## TODO: set your model hyperparameters
# define and print the net
n_hidden=128
n_layers=2

net = CharRNN(chars, n_hidden, n_layers)
print(net)

CharRNN(
  (lstm): LSTM(83, 128, num_layers=2, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.5, inplace=False)
  (fc): Linear(in_features=128, out_features=83, bias=True)
)


### Set your training hyperparameters!

In [160]:
batch_size = 5
seq_length = 10
n_epochs = 2 # start small if you are just testing initial behavior

# train the model
train(net, encoded, epochs=n_epochs, batch_size=batch_size, seq_length=seq_length, lr=0.001, print_every=10)

Epoch: 1/2... Step: 10... Loss: 4.2203... Val Loss: 4.1860
Epoch: 1/2... Step: 20... Loss: 3.7499... Val Loss: 3.2993
Epoch: 1/2... Step: 30... Loss: 2.9700... Val Loss: 3.1941
Epoch: 1/2... Step: 40... Loss: 3.1026... Val Loss: 3.1604
Epoch: 1/2... Step: 50... Loss: 3.3272... Val Loss: 3.1542
Epoch: 1/2... Step: 60... Loss: 3.0698... Val Loss: 3.1527
Epoch: 1/2... Step: 70... Loss: 3.1516... Val Loss: 3.1493
Epoch: 1/2... Step: 80... Loss: 3.4242... Val Loss: 3.1498
Epoch: 1/2... Step: 90... Loss: 3.1439... Val Loss: 3.1415
Epoch: 1/2... Step: 100... Loss: 2.9996... Val Loss: 3.1431
Epoch: 1/2... Step: 110... Loss: 3.2460... Val Loss: 3.1371
Epoch: 1/2... Step: 120... Loss: 3.1153... Val Loss: 3.1371
Epoch: 1/2... Step: 130... Loss: 3.2650... Val Loss: 3.1382
Epoch: 1/2... Step: 140... Loss: 3.1323... Val Loss: 3.1366
Epoch: 1/2... Step: 150... Loss: 3.0706... Val Loss: 3.1361
Epoch: 1/2... Step: 160... Loss: 2.9849... Val Loss: 3.1383
Epoch: 1/2... Step: 170... Loss: 3.1636... Val Lo

Epoch: 1/2... Step: 1380... Loss: 2.5197... Val Loss: 2.4947
Epoch: 1/2... Step: 1390... Loss: 2.5407... Val Loss: 2.4836
Epoch: 1/2... Step: 1400... Loss: 2.4453... Val Loss: 2.4845
Epoch: 1/2... Step: 1410... Loss: 2.2981... Val Loss: 2.4859
Epoch: 1/2... Step: 1420... Loss: 2.6600... Val Loss: 2.4804
Epoch: 1/2... Step: 1430... Loss: 2.5009... Val Loss: 2.4721
Epoch: 1/2... Step: 1440... Loss: 2.4470... Val Loss: 2.4776
Epoch: 1/2... Step: 1450... Loss: 2.5882... Val Loss: 2.4760
Epoch: 1/2... Step: 1460... Loss: 2.4416... Val Loss: 2.4706
Epoch: 1/2... Step: 1470... Loss: 2.6153... Val Loss: 2.4614
Epoch: 1/2... Step: 1480... Loss: 2.2979... Val Loss: 2.4683
Epoch: 1/2... Step: 1490... Loss: 2.5825... Val Loss: 2.4635
Epoch: 1/2... Step: 1500... Loss: 2.2846... Val Loss: 2.4632
Epoch: 1/2... Step: 1510... Loss: 2.5546... Val Loss: 2.4573
Epoch: 1/2... Step: 1520... Loss: 2.5770... Val Loss: 2.4748
Epoch: 1/2... Step: 1530... Loss: 2.6993... Val Loss: 2.4487
Epoch: 1/2... Step: 1540

Epoch: 1/2... Step: 2730... Loss: 2.4063... Val Loss: 2.2834
Epoch: 1/2... Step: 2740... Loss: 2.3776... Val Loss: 2.2824
Epoch: 1/2... Step: 2750... Loss: 2.2476... Val Loss: 2.2805
Epoch: 1/2... Step: 2760... Loss: 2.4903... Val Loss: 2.2872
Epoch: 1/2... Step: 2770... Loss: 2.8871... Val Loss: 2.2845
Epoch: 1/2... Step: 2780... Loss: 2.4752... Val Loss: 2.2838
Epoch: 1/2... Step: 2790... Loss: 2.2670... Val Loss: 2.2961
Epoch: 1/2... Step: 2800... Loss: 2.5134... Val Loss: 2.2844
Epoch: 1/2... Step: 2810... Loss: 2.0387... Val Loss: 2.2775
Epoch: 1/2... Step: 2820... Loss: 2.5155... Val Loss: 2.2794
Epoch: 1/2... Step: 2830... Loss: 2.0192... Val Loss: 2.2742
Epoch: 1/2... Step: 2840... Loss: 2.2036... Val Loss: 2.2724
Epoch: 1/2... Step: 2850... Loss: 2.2813... Val Loss: 2.2689
Epoch: 1/2... Step: 2860... Loss: 2.5052... Val Loss: 2.2724
Epoch: 1/2... Step: 2870... Loss: 2.2835... Val Loss: 2.2783
Epoch: 1/2... Step: 2880... Loss: 2.3503... Val Loss: 2.2763
Epoch: 1/2... Step: 2890

Epoch: 1/2... Step: 4080... Loss: 2.6574... Val Loss: 2.1795
Epoch: 1/2... Step: 4090... Loss: 2.2252... Val Loss: 2.1891
Epoch: 1/2... Step: 4100... Loss: 1.9132... Val Loss: 2.1693
Epoch: 1/2... Step: 4110... Loss: 2.4138... Val Loss: 2.1720
Epoch: 1/2... Step: 4120... Loss: 2.0319... Val Loss: 2.1702
Epoch: 1/2... Step: 4130... Loss: 2.2766... Val Loss: 2.1696
Epoch: 1/2... Step: 4140... Loss: 2.8690... Val Loss: 2.1749
Epoch: 1/2... Step: 4150... Loss: 2.1684... Val Loss: 2.1690
Epoch: 1/2... Step: 4160... Loss: 1.9985... Val Loss: 2.1736
Epoch: 1/2... Step: 4170... Loss: 2.0290... Val Loss: 2.1775
Epoch: 1/2... Step: 4180... Loss: 2.0660... Val Loss: 2.1714
Epoch: 1/2... Step: 4190... Loss: 1.8941... Val Loss: 2.1663
Epoch: 1/2... Step: 4200... Loss: 2.4183... Val Loss: 2.1647
Epoch: 1/2... Step: 4210... Loss: 2.2908... Val Loss: 2.1578
Epoch: 1/2... Step: 4220... Loss: 2.4806... Val Loss: 2.1579
Epoch: 1/2... Step: 4230... Loss: 2.0418... Val Loss: 2.1541
Epoch: 1/2... Step: 4240

Epoch: 1/2... Step: 5430... Loss: 2.2149... Val Loss: 2.0926
Epoch: 1/2... Step: 5440... Loss: 2.1862... Val Loss: 2.0914
Epoch: 1/2... Step: 5450... Loss: 2.0719... Val Loss: 2.0843
Epoch: 1/2... Step: 5460... Loss: 1.9238... Val Loss: 2.0788
Epoch: 1/2... Step: 5470... Loss: 2.1348... Val Loss: 2.0827
Epoch: 1/2... Step: 5480... Loss: 1.8173... Val Loss: 2.0782
Epoch: 1/2... Step: 5490... Loss: 2.1514... Val Loss: 2.0779
Epoch: 1/2... Step: 5500... Loss: 2.2329... Val Loss: 2.0804
Epoch: 1/2... Step: 5510... Loss: 1.9233... Val Loss: 2.0819
Epoch: 1/2... Step: 5520... Loss: 2.1604... Val Loss: 2.0804
Epoch: 1/2... Step: 5530... Loss: 2.1498... Val Loss: 2.0850
Epoch: 1/2... Step: 5540... Loss: 1.9622... Val Loss: 2.0810
Epoch: 1/2... Step: 5550... Loss: 1.9141... Val Loss: 2.0838
Epoch: 1/2... Step: 5560... Loss: 1.8447... Val Loss: 2.0825
Epoch: 1/2... Step: 5570... Loss: 2.0424... Val Loss: 2.0821
Epoch: 1/2... Step: 5580... Loss: 1.8469... Val Loss: 2.0810
Epoch: 1/2... Step: 5590

Epoch: 1/2... Step: 6780... Loss: 2.2003... Val Loss: 2.0175
Epoch: 1/2... Step: 6790... Loss: 1.9341... Val Loss: 2.0172
Epoch: 1/2... Step: 6800... Loss: 1.8180... Val Loss: 2.0210
Epoch: 1/2... Step: 6810... Loss: 1.8822... Val Loss: 2.0184
Epoch: 1/2... Step: 6820... Loss: 1.8002... Val Loss: 2.0190
Epoch: 1/2... Step: 6830... Loss: 1.8111... Val Loss: 2.0182
Epoch: 1/2... Step: 6840... Loss: 2.3751... Val Loss: 2.0143
Epoch: 1/2... Step: 6850... Loss: 1.8493... Val Loss: 2.0176
Epoch: 1/2... Step: 6860... Loss: 2.3464... Val Loss: 2.0231
Epoch: 1/2... Step: 6870... Loss: 2.5894... Val Loss: 2.0290
Epoch: 1/2... Step: 6880... Loss: 2.3411... Val Loss: 2.0257
Epoch: 1/2... Step: 6890... Loss: 2.1472... Val Loss: 2.0263
Epoch: 1/2... Step: 6900... Loss: 1.7411... Val Loss: 2.0269
Epoch: 1/2... Step: 6910... Loss: 2.2127... Val Loss: 2.0265
Epoch: 1/2... Step: 6920... Loss: 2.4928... Val Loss: 2.0301
Epoch: 1/2... Step: 6930... Loss: 1.9225... Val Loss: 2.0339
Epoch: 1/2... Step: 6940

Epoch: 1/2... Step: 8130... Loss: 2.2227... Val Loss: 1.9859
Epoch: 1/2... Step: 8140... Loss: 2.2220... Val Loss: 1.9845
Epoch: 1/2... Step: 8150... Loss: 2.8762... Val Loss: 1.9880
Epoch: 1/2... Step: 8160... Loss: 1.7723... Val Loss: 1.9862
Epoch: 1/2... Step: 8170... Loss: 2.0978... Val Loss: 1.9843
Epoch: 1/2... Step: 8180... Loss: 2.1290... Val Loss: 1.9809
Epoch: 1/2... Step: 8190... Loss: 1.8272... Val Loss: 1.9858
Epoch: 1/2... Step: 8200... Loss: 2.1338... Val Loss: 1.9832
Epoch: 1/2... Step: 8210... Loss: 2.0193... Val Loss: 1.9799
Epoch: 1/2... Step: 8220... Loss: 2.0897... Val Loss: 1.9791
Epoch: 1/2... Step: 8230... Loss: 2.4009... Val Loss: 1.9760
Epoch: 1/2... Step: 8240... Loss: 1.9270... Val Loss: 1.9799
Epoch: 1/2... Step: 8250... Loss: 1.6690... Val Loss: 1.9815
Epoch: 1/2... Step: 8260... Loss: 2.2195... Val Loss: 1.9809
Epoch: 1/2... Step: 8270... Loss: 2.1730... Val Loss: 1.9748
Epoch: 1/2... Step: 8280... Loss: 1.7091... Val Loss: 1.9771
Epoch: 1/2... Step: 8290

Epoch: 1/2... Step: 9480... Loss: 1.7024... Val Loss: 1.9402
Epoch: 1/2... Step: 9490... Loss: 2.0158... Val Loss: 1.9393
Epoch: 1/2... Step: 9500... Loss: 1.9242... Val Loss: 1.9390
Epoch: 1/2... Step: 9510... Loss: 1.6963... Val Loss: 1.9375
Epoch: 1/2... Step: 9520... Loss: 2.0417... Val Loss: 1.9391
Epoch: 1/2... Step: 9530... Loss: 1.9915... Val Loss: 1.9353
Epoch: 1/2... Step: 9540... Loss: 1.6864... Val Loss: 1.9339
Epoch: 1/2... Step: 9550... Loss: 1.8395... Val Loss: 1.9346
Epoch: 1/2... Step: 9560... Loss: 2.1642... Val Loss: 1.9372
Epoch: 1/2... Step: 9570... Loss: 1.9345... Val Loss: 1.9363
Epoch: 1/2... Step: 9580... Loss: 2.2319... Val Loss: 1.9364
Epoch: 1/2... Step: 9590... Loss: 2.1976... Val Loss: 1.9421
Epoch: 1/2... Step: 9600... Loss: 2.0264... Val Loss: 1.9453
Epoch: 1/2... Step: 9610... Loss: 1.8282... Val Loss: 1.9433
Epoch: 1/2... Step: 9620... Loss: 1.8593... Val Loss: 1.9372
Epoch: 1/2... Step: 9630... Loss: 1.9326... Val Loss: 1.9344
Epoch: 1/2... Step: 9640

Epoch: 1/2... Step: 10810... Loss: 1.9584... Val Loss: 1.9175
Epoch: 1/2... Step: 10820... Loss: 1.9610... Val Loss: 1.9170
Epoch: 1/2... Step: 10830... Loss: 1.7877... Val Loss: 1.9180
Epoch: 1/2... Step: 10840... Loss: 1.7060... Val Loss: 1.9180
Epoch: 1/2... Step: 10850... Loss: 1.7266... Val Loss: 1.9215
Epoch: 1/2... Step: 10860... Loss: 1.8528... Val Loss: 1.9115
Epoch: 1/2... Step: 10870... Loss: 1.7313... Val Loss: 1.9154
Epoch: 1/2... Step: 10880... Loss: 2.4428... Val Loss: 1.9156
Epoch: 1/2... Step: 10890... Loss: 1.5707... Val Loss: 1.9148
Epoch: 1/2... Step: 10900... Loss: 1.8207... Val Loss: 1.9144
Epoch: 1/2... Step: 10910... Loss: 2.0155... Val Loss: 1.9076
Epoch: 1/2... Step: 10920... Loss: 2.1293... Val Loss: 1.9102
Epoch: 1/2... Step: 10930... Loss: 1.4844... Val Loss: 1.9107
Epoch: 1/2... Step: 10940... Loss: 1.9871... Val Loss: 1.9081
Epoch: 1/2... Step: 10950... Loss: 1.9088... Val Loss: 1.9080
Epoch: 1/2... Step: 10960... Loss: 1.6610... Val Loss: 1.9093
Epoch: 1

Epoch: 1/2... Step: 12140... Loss: 1.8304... Val Loss: 1.8904
Epoch: 1/2... Step: 12150... Loss: 2.1314... Val Loss: 1.8848
Epoch: 1/2... Step: 12160... Loss: 1.8625... Val Loss: 1.8886
Epoch: 1/2... Step: 12170... Loss: 1.7198... Val Loss: 1.8907
Epoch: 1/2... Step: 12180... Loss: 1.8110... Val Loss: 1.8934
Epoch: 1/2... Step: 12190... Loss: 2.1736... Val Loss: 1.8901
Epoch: 1/2... Step: 12200... Loss: 1.4496... Val Loss: 1.8920
Epoch: 1/2... Step: 12210... Loss: 1.8899... Val Loss: 1.8947
Epoch: 1/2... Step: 12220... Loss: 2.1465... Val Loss: 1.8938
Epoch: 1/2... Step: 12230... Loss: 1.7683... Val Loss: 1.8943
Epoch: 1/2... Step: 12240... Loss: 1.5584... Val Loss: 1.8917
Epoch: 1/2... Step: 12250... Loss: 1.9600... Val Loss: 1.8906
Epoch: 1/2... Step: 12260... Loss: 1.9137... Val Loss: 1.8860
Epoch: 1/2... Step: 12270... Loss: 2.0437... Val Loss: 1.8884
Epoch: 1/2... Step: 12280... Loss: 1.9972... Val Loss: 1.8935
Epoch: 1/2... Step: 12290... Loss: 1.9380... Val Loss: 1.8978
Epoch: 1

Epoch: 1/2... Step: 13470... Loss: 2.2101... Val Loss: 1.8674
Epoch: 1/2... Step: 13480... Loss: 2.3361... Val Loss: 1.8696
Epoch: 1/2... Step: 13490... Loss: 2.2849... Val Loss: 1.8670
Epoch: 1/2... Step: 13500... Loss: 1.5890... Val Loss: 1.8658
Epoch: 1/2... Step: 13510... Loss: 1.9127... Val Loss: 1.8659
Epoch: 1/2... Step: 13520... Loss: 2.1676... Val Loss: 1.8627
Epoch: 1/2... Step: 13530... Loss: 1.9622... Val Loss: 1.8635
Epoch: 1/2... Step: 13540... Loss: 1.9439... Val Loss: 1.8670
Epoch: 1/2... Step: 13550... Loss: 1.6619... Val Loss: 1.8681
Epoch: 1/2... Step: 13560... Loss: 1.9619... Val Loss: 1.8677
Epoch: 1/2... Step: 13570... Loss: 1.7775... Val Loss: 1.8651
Epoch: 1/2... Step: 13580... Loss: 1.7678... Val Loss: 1.8614
Epoch: 1/2... Step: 13590... Loss: 1.8830... Val Loss: 1.8570
Epoch: 1/2... Step: 13600... Loss: 1.9936... Val Loss: 1.8541
Epoch: 1/2... Step: 13610... Loss: 2.0608... Val Loss: 1.8591
Epoch: 1/2... Step: 13620... Loss: 1.5711... Val Loss: 1.8591
Epoch: 1

Epoch: 1/2... Step: 14800... Loss: 1.8569... Val Loss: 1.8336
Epoch: 1/2... Step: 14810... Loss: 1.6162... Val Loss: 1.8321
Epoch: 1/2... Step: 14820... Loss: 1.5510... Val Loss: 1.8317
Epoch: 1/2... Step: 14830... Loss: 1.8803... Val Loss: 1.8329
Epoch: 1/2... Step: 14840... Loss: 2.0489... Val Loss: 1.8336
Epoch: 1/2... Step: 14850... Loss: 1.7819... Val Loss: 1.8366
Epoch: 1/2... Step: 14860... Loss: 1.9026... Val Loss: 1.8387
Epoch: 1/2... Step: 14870... Loss: 1.4693... Val Loss: 1.8375
Epoch: 1/2... Step: 14880... Loss: 1.6753... Val Loss: 1.8361
Epoch: 1/2... Step: 14890... Loss: 1.5117... Val Loss: 1.8340
Epoch: 1/2... Step: 14900... Loss: 2.1701... Val Loss: 1.8325
Epoch: 1/2... Step: 14910... Loss: 1.8848... Val Loss: 1.8315
Epoch: 1/2... Step: 14920... Loss: 2.0638... Val Loss: 1.8334
Epoch: 1/2... Step: 14930... Loss: 1.6668... Val Loss: 1.8349
Epoch: 1/2... Step: 14940... Loss: 1.8391... Val Loss: 1.8343
Epoch: 1/2... Step: 14950... Loss: 1.9187... Val Loss: 1.8324
Epoch: 1

Epoch: 1/2... Step: 16130... Loss: 1.8417... Val Loss: 1.8211
Epoch: 1/2... Step: 16140... Loss: 1.8136... Val Loss: 1.8184
Epoch: 1/2... Step: 16150... Loss: 2.1373... Val Loss: 1.8191
Epoch: 1/2... Step: 16160... Loss: 2.2445... Val Loss: 1.8173
Epoch: 1/2... Step: 16170... Loss: 1.9078... Val Loss: 1.8193
Epoch: 1/2... Step: 16180... Loss: 1.6010... Val Loss: 1.8157
Epoch: 1/2... Step: 16190... Loss: 1.9692... Val Loss: 1.8167
Epoch: 1/2... Step: 16200... Loss: 2.1497... Val Loss: 1.8136
Epoch: 1/2... Step: 16210... Loss: 1.4956... Val Loss: 1.8139
Epoch: 1/2... Step: 16220... Loss: 1.7596... Val Loss: 1.8154
Epoch: 1/2... Step: 16230... Loss: 1.7654... Val Loss: 1.8156
Epoch: 1/2... Step: 16240... Loss: 1.8128... Val Loss: 1.8194
Epoch: 1/2... Step: 16250... Loss: 2.1240... Val Loss: 1.8172
Epoch: 1/2... Step: 16260... Loss: 2.1168... Val Loss: 1.8149
Epoch: 1/2... Step: 16270... Loss: 1.7810... Val Loss: 1.8135
Epoch: 1/2... Step: 16280... Loss: 1.6627... Val Loss: 1.8128
Epoch: 1

Epoch: 1/2... Step: 17460... Loss: 1.9791... Val Loss: 1.8075
Epoch: 1/2... Step: 17470... Loss: 1.7322... Val Loss: 1.8064
Epoch: 1/2... Step: 17480... Loss: 2.0113... Val Loss: 1.8045
Epoch: 1/2... Step: 17490... Loss: 1.7484... Val Loss: 1.8049
Epoch: 1/2... Step: 17500... Loss: 1.3307... Val Loss: 1.8098
Epoch: 1/2... Step: 17510... Loss: 1.4581... Val Loss: 1.8175
Epoch: 1/2... Step: 17520... Loss: 2.0950... Val Loss: 1.8179
Epoch: 1/2... Step: 17530... Loss: 2.1616... Val Loss: 1.8080
Epoch: 1/2... Step: 17540... Loss: 1.7001... Val Loss: 1.8041
Epoch: 1/2... Step: 17550... Loss: 1.8083... Val Loss: 1.8038
Epoch: 1/2... Step: 17560... Loss: 1.9232... Val Loss: 1.8034
Epoch: 1/2... Step: 17570... Loss: 2.0425... Val Loss: 1.8043
Epoch: 1/2... Step: 17580... Loss: 1.7107... Val Loss: 1.8040
Epoch: 1/2... Step: 17590... Loss: 2.1171... Val Loss: 1.8021
Epoch: 1/2... Step: 17600... Loss: 1.2224... Val Loss: 1.8010
Epoch: 1/2... Step: 17610... Loss: 1.8837... Val Loss: 1.7991
Epoch: 1

Epoch: 1/2... Step: 18790... Loss: 1.9442... Val Loss: 1.8018
Epoch: 1/2... Step: 18800... Loss: 1.6713... Val Loss: 1.7997
Epoch: 1/2... Step: 18810... Loss: 2.0894... Val Loss: 1.7992
Epoch: 1/2... Step: 18820... Loss: 2.2012... Val Loss: 1.7972
Epoch: 1/2... Step: 18830... Loss: 2.0967... Val Loss: 1.7977
Epoch: 1/2... Step: 18840... Loss: 1.6022... Val Loss: 1.7947
Epoch: 1/2... Step: 18850... Loss: 2.1266... Val Loss: 1.7926
Epoch: 1/2... Step: 18860... Loss: 1.6792... Val Loss: 1.7898
Epoch: 1/2... Step: 18870... Loss: 1.8797... Val Loss: 1.7893
Epoch: 1/2... Step: 18880... Loss: 1.5937... Val Loss: 1.7901
Epoch: 1/2... Step: 18890... Loss: 1.7661... Val Loss: 1.7906
Epoch: 1/2... Step: 18900... Loss: 1.6774... Val Loss: 1.7903
Epoch: 1/2... Step: 18910... Loss: 1.6955... Val Loss: 1.7890
Epoch: 1/2... Step: 18920... Loss: 2.0944... Val Loss: 1.7871
Epoch: 1/2... Step: 18930... Loss: 1.6916... Val Loss: 1.7871
Epoch: 1/2... Step: 18940... Loss: 2.4793... Val Loss: 1.7887
Epoch: 1

Epoch: 1/2... Step: 20120... Loss: 1.5966... Val Loss: 1.7807
Epoch: 1/2... Step: 20130... Loss: 1.4425... Val Loss: 1.7805
Epoch: 1/2... Step: 20140... Loss: 1.9995... Val Loss: 1.7790
Epoch: 1/2... Step: 20150... Loss: 1.7208... Val Loss: 1.7776
Epoch: 1/2... Step: 20160... Loss: 1.7560... Val Loss: 1.7760
Epoch: 1/2... Step: 20170... Loss: 1.5929... Val Loss: 1.7748
Epoch: 1/2... Step: 20180... Loss: 1.6074... Val Loss: 1.7745
Epoch: 1/2... Step: 20190... Loss: 1.9341... Val Loss: 1.7746
Epoch: 1/2... Step: 20200... Loss: 2.0143... Val Loss: 1.7764
Epoch: 1/2... Step: 20210... Loss: 1.5070... Val Loss: 1.7767
Epoch: 1/2... Step: 20220... Loss: 1.8655... Val Loss: 1.7759
Epoch: 1/2... Step: 20230... Loss: 1.6109... Val Loss: 1.7762
Epoch: 1/2... Step: 20240... Loss: 1.7497... Val Loss: 1.7769
Epoch: 1/2... Step: 20250... Loss: 1.7552... Val Loss: 1.7786
Epoch: 1/2... Step: 20260... Loss: 1.5106... Val Loss: 1.7774
Epoch: 1/2... Step: 20270... Loss: 1.7588... Val Loss: 1.7786
Epoch: 1

Epoch: 1/2... Step: 21450... Loss: 1.9281... Val Loss: 1.7621
Epoch: 1/2... Step: 21460... Loss: 1.3883... Val Loss: 1.7613
Epoch: 1/2... Step: 21470... Loss: 1.9181... Val Loss: 1.7620
Epoch: 1/2... Step: 21480... Loss: 1.5330... Val Loss: 1.7606
Epoch: 1/2... Step: 21490... Loss: 1.8103... Val Loss: 1.7619
Epoch: 1/2... Step: 21500... Loss: 1.5950... Val Loss: 1.7616
Epoch: 1/2... Step: 21510... Loss: 1.2836... Val Loss: 1.7609
Epoch: 1/2... Step: 21520... Loss: 1.8386... Val Loss: 1.7599
Epoch: 1/2... Step: 21530... Loss: 1.7170... Val Loss: 1.7610
Epoch: 1/2... Step: 21540... Loss: 1.7219... Val Loss: 1.7654
Epoch: 1/2... Step: 21550... Loss: 1.8635... Val Loss: 1.7622
Epoch: 1/2... Step: 21560... Loss: 2.2131... Val Loss: 1.7557
Epoch: 1/2... Step: 21570... Loss: 1.7227... Val Loss: 1.7548
Epoch: 1/2... Step: 21580... Loss: 1.6247... Val Loss: 1.7548
Epoch: 1/2... Step: 21590... Loss: 1.8981... Val Loss: 1.7552
Epoch: 1/2... Step: 21600... Loss: 1.7854... Val Loss: 1.7557
Epoch: 1

Epoch: 1/2... Step: 22780... Loss: 2.0056... Val Loss: 1.7445
Epoch: 1/2... Step: 22790... Loss: 1.7856... Val Loss: 1.7457
Epoch: 1/2... Step: 22800... Loss: 2.0853... Val Loss: 1.7479
Epoch: 1/2... Step: 22810... Loss: 1.8271... Val Loss: 1.7491
Epoch: 1/2... Step: 22820... Loss: 2.3020... Val Loss: 1.7470
Epoch: 1/2... Step: 22830... Loss: 1.7094... Val Loss: 1.7470
Epoch: 1/2... Step: 22840... Loss: 1.9189... Val Loss: 1.7470
Epoch: 1/2... Step: 22850... Loss: 1.7157... Val Loss: 1.7476
Epoch: 1/2... Step: 22860... Loss: 1.9305... Val Loss: 1.7492
Epoch: 1/2... Step: 22870... Loss: 1.6666... Val Loss: 1.7480
Epoch: 1/2... Step: 22880... Loss: 2.1147... Val Loss: 1.7480
Epoch: 1/2... Step: 22890... Loss: 1.7740... Val Loss: 1.7478
Epoch: 1/2... Step: 22900... Loss: 1.8536... Val Loss: 1.7474
Epoch: 1/2... Step: 22910... Loss: 1.6362... Val Loss: 1.7437
Epoch: 1/2... Step: 22920... Loss: 1.5398... Val Loss: 1.7427
Epoch: 1/2... Step: 22930... Loss: 1.5645... Val Loss: 1.7434
Epoch: 1

Epoch: 1/2... Step: 24110... Loss: 1.5693... Val Loss: 1.7361
Epoch: 1/2... Step: 24120... Loss: 1.7730... Val Loss: 1.7414
Epoch: 1/2... Step: 24130... Loss: 1.8203... Val Loss: 1.7389
Epoch: 1/2... Step: 24140... Loss: 1.7726... Val Loss: 1.7337
Epoch: 1/2... Step: 24150... Loss: 1.7444... Val Loss: 1.7351
Epoch: 1/2... Step: 24160... Loss: 1.9323... Val Loss: 1.7367
Epoch: 1/2... Step: 24170... Loss: 1.4273... Val Loss: 1.7377
Epoch: 1/2... Step: 24180... Loss: 1.6081... Val Loss: 1.7393
Epoch: 1/2... Step: 24190... Loss: 1.5528... Val Loss: 1.7383
Epoch: 1/2... Step: 24200... Loss: 2.0257... Val Loss: 1.7397
Epoch: 1/2... Step: 24210... Loss: 1.7972... Val Loss: 1.7389
Epoch: 1/2... Step: 24220... Loss: 1.3652... Val Loss: 1.7381
Epoch: 1/2... Step: 24230... Loss: 1.3585... Val Loss: 1.7391
Epoch: 1/2... Step: 24240... Loss: 1.2415... Val Loss: 1.7415
Epoch: 1/2... Step: 24250... Loss: 1.3683... Val Loss: 1.7455
Epoch: 1/2... Step: 24260... Loss: 1.5469... Val Loss: 1.7480
Epoch: 1

Epoch: 1/2... Step: 25440... Loss: 1.5500... Val Loss: 1.7375
Epoch: 1/2... Step: 25450... Loss: 1.7246... Val Loss: 1.7358
Epoch: 1/2... Step: 25460... Loss: 1.4918... Val Loss: 1.7360
Epoch: 1/2... Step: 25470... Loss: 1.3694... Val Loss: 1.7371
Epoch: 1/2... Step: 25480... Loss: 1.8325... Val Loss: 1.7340
Epoch: 1/2... Step: 25490... Loss: 1.5437... Val Loss: 1.7350
Epoch: 1/2... Step: 25500... Loss: 1.9788... Val Loss: 1.7374
Epoch: 1/2... Step: 25510... Loss: 1.3514... Val Loss: 1.7387
Epoch: 1/2... Step: 25520... Loss: 1.6411... Val Loss: 1.7357
Epoch: 1/2... Step: 25530... Loss: 1.2242... Val Loss: 1.7335
Epoch: 1/2... Step: 25540... Loss: 2.1317... Val Loss: 1.7340
Epoch: 1/2... Step: 25550... Loss: 1.8100... Val Loss: 1.7336
Epoch: 1/2... Step: 25560... Loss: 1.6367... Val Loss: 1.7351
Epoch: 1/2... Step: 25570... Loss: 1.9280... Val Loss: 1.7367
Epoch: 1/2... Step: 25580... Loss: 1.4281... Val Loss: 1.7403
Epoch: 1/2... Step: 25590... Loss: 2.5649... Val Loss: 1.7407
Epoch: 1

Epoch: 1/2... Step: 26770... Loss: 1.8340... Val Loss: 1.7172
Epoch: 1/2... Step: 26780... Loss: 1.5537... Val Loss: 1.7156
Epoch: 1/2... Step: 26790... Loss: 1.8251... Val Loss: 1.7136
Epoch: 1/2... Step: 26800... Loss: 1.9466... Val Loss: 1.7152
Epoch: 1/2... Step: 26810... Loss: 1.2510... Val Loss: 1.7162
Epoch: 1/2... Step: 26820... Loss: 1.9430... Val Loss: 1.7174
Epoch: 1/2... Step: 26830... Loss: 1.9866... Val Loss: 1.7201
Epoch: 1/2... Step: 26840... Loss: 1.5198... Val Loss: 1.7210
Epoch: 1/2... Step: 26850... Loss: 1.6195... Val Loss: 1.7198
Epoch: 1/2... Step: 26860... Loss: 1.3206... Val Loss: 1.7210
Epoch: 1/2... Step: 26870... Loss: 2.0481... Val Loss: 1.7234
Epoch: 1/2... Step: 26880... Loss: 1.8999... Val Loss: 1.7266
Epoch: 1/2... Step: 26890... Loss: 1.7250... Val Loss: 1.7292
Epoch: 1/2... Step: 26900... Loss: 1.7109... Val Loss: 1.7287
Epoch: 1/2... Step: 26910... Loss: 1.5405... Val Loss: 1.7294
Epoch: 1/2... Step: 26920... Loss: 1.6141... Val Loss: 1.7278
Epoch: 1

Epoch: 1/2... Step: 28100... Loss: 2.0108... Val Loss: 1.7131
Epoch: 1/2... Step: 28110... Loss: 2.1893... Val Loss: 1.7111
Epoch: 1/2... Step: 28120... Loss: 1.7766... Val Loss: 1.7098
Epoch: 1/2... Step: 28130... Loss: 1.5374... Val Loss: 1.7084
Epoch: 1/2... Step: 28140... Loss: 1.8741... Val Loss: 1.7109
Epoch: 1/2... Step: 28150... Loss: 1.5574... Val Loss: 1.7129
Epoch: 1/2... Step: 28160... Loss: 1.6090... Val Loss: 1.7129
Epoch: 1/2... Step: 28170... Loss: 1.3436... Val Loss: 1.7116
Epoch: 1/2... Step: 28180... Loss: 1.4767... Val Loss: 1.7128
Epoch: 1/2... Step: 28190... Loss: 2.1511... Val Loss: 1.7122
Epoch: 1/2... Step: 28200... Loss: 1.8645... Val Loss: 1.7126
Epoch: 1/2... Step: 28210... Loss: 1.5906... Val Loss: 1.7124
Epoch: 1/2... Step: 28220... Loss: 1.8152... Val Loss: 1.7127
Epoch: 1/2... Step: 28230... Loss: 2.1893... Val Loss: 1.7125
Epoch: 1/2... Step: 28240... Loss: 2.0174... Val Loss: 1.7134
Epoch: 1/2... Step: 28250... Loss: 2.0894... Val Loss: 1.7146
Epoch: 1

Epoch: 1/2... Step: 29430... Loss: 1.4832... Val Loss: 1.7124
Epoch: 1/2... Step: 29440... Loss: 1.5070... Val Loss: 1.7106
Epoch: 1/2... Step: 29450... Loss: 1.5269... Val Loss: 1.7093
Epoch: 1/2... Step: 29460... Loss: 1.5367... Val Loss: 1.7107
Epoch: 1/2... Step: 29470... Loss: 1.5386... Val Loss: 1.7150
Epoch: 1/2... Step: 29480... Loss: 1.5470... Val Loss: 1.7142
Epoch: 1/2... Step: 29490... Loss: 2.2111... Val Loss: 1.7109
Epoch: 1/2... Step: 29500... Loss: 2.1726... Val Loss: 1.7126
Epoch: 1/2... Step: 29510... Loss: 1.4491... Val Loss: 1.7145
Epoch: 1/2... Step: 29520... Loss: 1.5418... Val Loss: 1.7153
Epoch: 1/2... Step: 29530... Loss: 1.2936... Val Loss: 1.7149
Epoch: 1/2... Step: 29540... Loss: 1.5690... Val Loss: 1.7149
Epoch: 1/2... Step: 29550... Loss: 1.3793... Val Loss: 1.7154
Epoch: 1/2... Step: 29560... Loss: 1.3428... Val Loss: 1.7161
Epoch: 1/2... Step: 29570... Loss: 1.4501... Val Loss: 1.7131
Epoch: 1/2... Step: 29580... Loss: 1.5576... Val Loss: 1.7119
Epoch: 1

Epoch: 1/2... Step: 30760... Loss: 1.6286... Val Loss: 1.7025
Epoch: 1/2... Step: 30770... Loss: 1.9905... Val Loss: 1.7024
Epoch: 1/2... Step: 30780... Loss: 1.9621... Val Loss: 1.7014
Epoch: 1/2... Step: 30790... Loss: 1.4637... Val Loss: 1.7030
Epoch: 1/2... Step: 30800... Loss: 1.7594... Val Loss: 1.7056
Epoch: 1/2... Step: 30810... Loss: 1.7787... Val Loss: 1.7058
Epoch: 1/2... Step: 30820... Loss: 1.9395... Val Loss: 1.7066
Epoch: 1/2... Step: 30830... Loss: 2.2826... Val Loss: 1.7071
Epoch: 1/2... Step: 30840... Loss: 1.9812... Val Loss: 1.7052
Epoch: 1/2... Step: 30850... Loss: 1.0390... Val Loss: 1.7061
Epoch: 1/2... Step: 30860... Loss: 1.7935... Val Loss: 1.7066
Epoch: 1/2... Step: 30870... Loss: 1.9912... Val Loss: 1.7043
Epoch: 1/2... Step: 30880... Loss: 1.5661... Val Loss: 1.7037
Epoch: 1/2... Step: 30890... Loss: 1.9634... Val Loss: 1.7055
Epoch: 1/2... Step: 30900... Loss: 1.8856... Val Loss: 1.7092
Epoch: 1/2... Step: 30910... Loss: 1.7260... Val Loss: 1.7103
Epoch: 1

Epoch: 1/2... Step: 32090... Loss: 1.6595... Val Loss: 1.6970
Epoch: 1/2... Step: 32100... Loss: 1.7951... Val Loss: 1.6967
Epoch: 1/2... Step: 32110... Loss: 1.5941... Val Loss: 1.6959
Epoch: 1/2... Step: 32120... Loss: 1.7809... Val Loss: 1.6981
Epoch: 1/2... Step: 32130... Loss: 1.8663... Val Loss: 1.7013
Epoch: 1/2... Step: 32140... Loss: 1.6715... Val Loss: 1.7035
Epoch: 1/2... Step: 32150... Loss: 1.5214... Val Loss: 1.7037
Epoch: 1/2... Step: 32160... Loss: 1.3837... Val Loss: 1.7025
Epoch: 1/2... Step: 32170... Loss: 1.6460... Val Loss: 1.7015
Epoch: 1/2... Step: 32180... Loss: 1.4861... Val Loss: 1.7016
Epoch: 1/2... Step: 32190... Loss: 1.5227... Val Loss: 1.7006
Epoch: 1/2... Step: 32200... Loss: 1.4486... Val Loss: 1.6995
Epoch: 1/2... Step: 32210... Loss: 1.5874... Val Loss: 1.6997
Epoch: 1/2... Step: 32220... Loss: 1.5022... Val Loss: 1.6982
Epoch: 1/2... Step: 32230... Loss: 1.3305... Val Loss: 1.6981
Epoch: 1/2... Step: 32240... Loss: 1.6344... Val Loss: 1.6967
Epoch: 1

Epoch: 1/2... Step: 33420... Loss: 1.6235... Val Loss: 1.6884
Epoch: 1/2... Step: 33430... Loss: 1.2760... Val Loss: 1.6881
Epoch: 1/2... Step: 33440... Loss: 1.4510... Val Loss: 1.6882
Epoch: 1/2... Step: 33450... Loss: 1.3616... Val Loss: 1.6898
Epoch: 1/2... Step: 33460... Loss: 1.9783... Val Loss: 1.6895
Epoch: 1/2... Step: 33470... Loss: 1.8460... Val Loss: 1.6894
Epoch: 1/2... Step: 33480... Loss: 1.8713... Val Loss: 1.6901
Epoch: 1/2... Step: 33490... Loss: 1.5082... Val Loss: 1.6907
Epoch: 1/2... Step: 33500... Loss: 1.5376... Val Loss: 1.6919
Epoch: 1/2... Step: 33510... Loss: 1.8271... Val Loss: 1.6921
Epoch: 1/2... Step: 33520... Loss: 1.9036... Val Loss: 1.6927
Epoch: 1/2... Step: 33530... Loss: 1.6625... Val Loss: 1.6927
Epoch: 1/2... Step: 33540... Loss: 1.5563... Val Loss: 1.6938
Epoch: 1/2... Step: 33550... Loss: 1.0482... Val Loss: 1.6952
Epoch: 1/2... Step: 33560... Loss: 1.9362... Val Loss: 1.6951
Epoch: 1/2... Step: 33570... Loss: 1.7018... Val Loss: 1.6938
Epoch: 1

Epoch: 1/2... Step: 34750... Loss: 1.7408... Val Loss: 1.6830
Epoch: 1/2... Step: 34760... Loss: 2.2295... Val Loss: 1.6803
Epoch: 1/2... Step: 34770... Loss: 1.7483... Val Loss: 1.6792
Epoch: 1/2... Step: 34780... Loss: 1.8521... Val Loss: 1.6801
Epoch: 1/2... Step: 34790... Loss: 1.6684... Val Loss: 1.6820
Epoch: 1/2... Step: 34800... Loss: 1.9465... Val Loss: 1.6821
Epoch: 1/2... Step: 34810... Loss: 1.4970... Val Loss: 1.6823
Epoch: 1/2... Step: 34820... Loss: 1.7404... Val Loss: 1.6822
Epoch: 1/2... Step: 34830... Loss: 2.1584... Val Loss: 1.6833
Epoch: 1/2... Step: 34840... Loss: 1.3408... Val Loss: 1.6830
Epoch: 1/2... Step: 34850... Loss: 2.5662... Val Loss: 1.6801
Epoch: 1/2... Step: 34860... Loss: 1.7421... Val Loss: 1.6781
Epoch: 1/2... Step: 34870... Loss: 1.6041... Val Loss: 1.6781
Epoch: 1/2... Step: 34880... Loss: 1.8512... Val Loss: 1.6791
Epoch: 1/2... Step: 34890... Loss: 1.6410... Val Loss: 1.6812
Epoch: 1/2... Step: 34900... Loss: 1.7860... Val Loss: 1.6814
Epoch: 1

Epoch: 2/2... Step: 36080... Loss: 1.9729... Val Loss: 1.6758
Epoch: 2/2... Step: 36090... Loss: 1.6820... Val Loss: 1.6775
Epoch: 2/2... Step: 36100... Loss: 1.7552... Val Loss: 1.6787
Epoch: 2/2... Step: 36110... Loss: 1.7084... Val Loss: 1.6795
Epoch: 2/2... Step: 36120... Loss: 1.6620... Val Loss: 1.6808
Epoch: 2/2... Step: 36130... Loss: 1.6312... Val Loss: 1.6802
Epoch: 2/2... Step: 36140... Loss: 1.4065... Val Loss: 1.6805
Epoch: 2/2... Step: 36150... Loss: 1.8501... Val Loss: 1.6822
Epoch: 2/2... Step: 36160... Loss: 1.4519... Val Loss: 1.6763
Epoch: 2/2... Step: 36170... Loss: 1.7390... Val Loss: 1.6738
Epoch: 2/2... Step: 36180... Loss: 1.6318... Val Loss: 1.6731
Epoch: 2/2... Step: 36190... Loss: 1.4007... Val Loss: 1.6732
Epoch: 2/2... Step: 36200... Loss: 1.8034... Val Loss: 1.6741
Epoch: 2/2... Step: 36210... Loss: 1.5724... Val Loss: 1.6736
Epoch: 2/2... Step: 36220... Loss: 1.7223... Val Loss: 1.6732
Epoch: 2/2... Step: 36230... Loss: 1.7058... Val Loss: 1.6726
Epoch: 2

Epoch: 2/2... Step: 37410... Loss: 1.4728... Val Loss: 1.6790
Epoch: 2/2... Step: 37420... Loss: 1.9896... Val Loss: 1.6771
Epoch: 2/2... Step: 37430... Loss: 1.5911... Val Loss: 1.6773
Epoch: 2/2... Step: 37440... Loss: 1.8091... Val Loss: 1.6766
Epoch: 2/2... Step: 37450... Loss: 1.9517... Val Loss: 1.6752
Epoch: 2/2... Step: 37460... Loss: 1.9840... Val Loss: 1.6756
Epoch: 2/2... Step: 37470... Loss: 2.2184... Val Loss: 1.6760
Epoch: 2/2... Step: 37480... Loss: 2.2084... Val Loss: 1.6756
Epoch: 2/2... Step: 37490... Loss: 1.9893... Val Loss: 1.6752
Epoch: 2/2... Step: 37500... Loss: 1.8513... Val Loss: 1.6740
Epoch: 2/2... Step: 37510... Loss: 1.8886... Val Loss: 1.6734
Epoch: 2/2... Step: 37520... Loss: 2.0373... Val Loss: 1.6724
Epoch: 2/2... Step: 37530... Loss: 1.5630... Val Loss: 1.6714
Epoch: 2/2... Step: 37540... Loss: 1.8201... Val Loss: 1.6712
Epoch: 2/2... Step: 37550... Loss: 1.3706... Val Loss: 1.6704
Epoch: 2/2... Step: 37560... Loss: 1.6462... Val Loss: 1.6708
Epoch: 2

Epoch: 2/2... Step: 38740... Loss: 1.7560... Val Loss: 1.6690
Epoch: 2/2... Step: 38750... Loss: 1.8001... Val Loss: 1.6691
Epoch: 2/2... Step: 38760... Loss: 1.5143... Val Loss: 1.6702
Epoch: 2/2... Step: 38770... Loss: 1.5416... Val Loss: 1.6695
Epoch: 2/2... Step: 38780... Loss: 1.6364... Val Loss: 1.6696
Epoch: 2/2... Step: 38790... Loss: 1.4656... Val Loss: 1.6696
Epoch: 2/2... Step: 38800... Loss: 1.5884... Val Loss: 1.6696
Epoch: 2/2... Step: 38810... Loss: 1.8297... Val Loss: 1.6683
Epoch: 2/2... Step: 38820... Loss: 1.8205... Val Loss: 1.6671
Epoch: 2/2... Step: 38830... Loss: 1.8479... Val Loss: 1.6659
Epoch: 2/2... Step: 38840... Loss: 2.0698... Val Loss: 1.6658
Epoch: 2/2... Step: 38850... Loss: 1.6272... Val Loss: 1.6674
Epoch: 2/2... Step: 38860... Loss: 1.7290... Val Loss: 1.6650
Epoch: 2/2... Step: 38870... Loss: 1.5737... Val Loss: 1.6646
Epoch: 2/2... Step: 38880... Loss: 1.7493... Val Loss: 1.6640
Epoch: 2/2... Step: 38890... Loss: 1.5201... Val Loss: 1.6641
Epoch: 2

Epoch: 2/2... Step: 40070... Loss: 1.5155... Val Loss: 1.6661
Epoch: 2/2... Step: 40080... Loss: 1.7376... Val Loss: 1.6677
Epoch: 2/2... Step: 40090... Loss: 1.6812... Val Loss: 1.6654
Epoch: 2/2... Step: 40100... Loss: 2.0353... Val Loss: 1.6642
Epoch: 2/2... Step: 40110... Loss: 2.2254... Val Loss: 1.6633
Epoch: 2/2... Step: 40120... Loss: 1.7683... Val Loss: 1.6629
Epoch: 2/2... Step: 40130... Loss: 1.7019... Val Loss: 1.6633
Epoch: 2/2... Step: 40140... Loss: 1.3960... Val Loss: 1.6631
Epoch: 2/2... Step: 40150... Loss: 1.4487... Val Loss: 1.6635
Epoch: 2/2... Step: 40160... Loss: 1.3196... Val Loss: 1.6641
Epoch: 2/2... Step: 40170... Loss: 1.5736... Val Loss: 1.6639
Epoch: 2/2... Step: 40180... Loss: 1.6124... Val Loss: 1.6641
Epoch: 2/2... Step: 40190... Loss: 1.5548... Val Loss: 1.6638
Epoch: 2/2... Step: 40200... Loss: 2.4031... Val Loss: 1.6646
Epoch: 2/2... Step: 40210... Loss: 2.0298... Val Loss: 1.6646
Epoch: 2/2... Step: 40220... Loss: 1.9101... Val Loss: 1.6653
Epoch: 2

Epoch: 2/2... Step: 41400... Loss: 1.7311... Val Loss: 1.6661
Epoch: 2/2... Step: 41410... Loss: 1.8466... Val Loss: 1.6670
Epoch: 2/2... Step: 41420... Loss: 2.2088... Val Loss: 1.6674
Epoch: 2/2... Step: 41430... Loss: 1.8961... Val Loss: 1.6678
Epoch: 2/2... Step: 41440... Loss: 1.7235... Val Loss: 1.6671
Epoch: 2/2... Step: 41450... Loss: 1.8864... Val Loss: 1.6666
Epoch: 2/2... Step: 41460... Loss: 1.8487... Val Loss: 1.6675
Epoch: 2/2... Step: 41470... Loss: 1.6155... Val Loss: 1.6674
Epoch: 2/2... Step: 41480... Loss: 1.5015... Val Loss: 1.6669
Epoch: 2/2... Step: 41490... Loss: 1.9278... Val Loss: 1.6656
Epoch: 2/2... Step: 41500... Loss: 1.9652... Val Loss: 1.6639
Epoch: 2/2... Step: 41510... Loss: 1.2803... Val Loss: 1.6637
Epoch: 2/2... Step: 41520... Loss: 1.9606... Val Loss: 1.6632
Epoch: 2/2... Step: 41530... Loss: 2.1849... Val Loss: 1.6643
Epoch: 2/2... Step: 41540... Loss: 1.7924... Val Loss: 1.6637
Epoch: 2/2... Step: 41550... Loss: 1.6457... Val Loss: 1.6644
Epoch: 2

Epoch: 2/2... Step: 42730... Loss: 2.0487... Val Loss: 1.6534
Epoch: 2/2... Step: 42740... Loss: 2.0032... Val Loss: 1.6527
Epoch: 2/2... Step: 42750... Loss: 2.0835... Val Loss: 1.6552
Epoch: 2/2... Step: 42760... Loss: 1.2886... Val Loss: 1.6558
Epoch: 2/2... Step: 42770... Loss: 3.2528... Val Loss: 1.6561
Epoch: 2/2... Step: 42780... Loss: 1.4069... Val Loss: 1.6557
Epoch: 2/2... Step: 42790... Loss: 1.8758... Val Loss: 1.6553
Epoch: 2/2... Step: 42800... Loss: 1.7563... Val Loss: 1.6551
Epoch: 2/2... Step: 42810... Loss: 1.5066... Val Loss: 1.6579
Epoch: 2/2... Step: 42820... Loss: 1.2789... Val Loss: 1.6596
Epoch: 2/2... Step: 42830... Loss: 1.2328... Val Loss: 1.6575
Epoch: 2/2... Step: 42840... Loss: 1.7191... Val Loss: 1.6573
Epoch: 2/2... Step: 42850... Loss: 1.4226... Val Loss: 1.6579
Epoch: 2/2... Step: 42860... Loss: 1.6591... Val Loss: 1.6560
Epoch: 2/2... Step: 42870... Loss: 1.4082... Val Loss: 1.6553
Epoch: 2/2... Step: 42880... Loss: 1.6983... Val Loss: 1.6561
Epoch: 2

Epoch: 2/2... Step: 44060... Loss: 1.7830... Val Loss: 1.6553
Epoch: 2/2... Step: 44070... Loss: 1.6505... Val Loss: 1.6539
Epoch: 2/2... Step: 44080... Loss: 1.7205... Val Loss: 1.6529
Epoch: 2/2... Step: 44090... Loss: 1.4215... Val Loss: 1.6532
Epoch: 2/2... Step: 44100... Loss: 1.6380... Val Loss: 1.6533
Epoch: 2/2... Step: 44110... Loss: 1.5313... Val Loss: 1.6551
Epoch: 2/2... Step: 44120... Loss: 2.2840... Val Loss: 1.6566
Epoch: 2/2... Step: 44130... Loss: 1.6084... Val Loss: 1.6570
Epoch: 2/2... Step: 44140... Loss: 1.7530... Val Loss: 1.6573
Epoch: 2/2... Step: 44150... Loss: 1.7164... Val Loss: 1.6575
Epoch: 2/2... Step: 44160... Loss: 1.9579... Val Loss: 1.6572
Epoch: 2/2... Step: 44170... Loss: 1.4718... Val Loss: 1.6578
Epoch: 2/2... Step: 44180... Loss: 1.1655... Val Loss: 1.6571
Epoch: 2/2... Step: 44190... Loss: 1.5681... Val Loss: 1.6563
Epoch: 2/2... Step: 44200... Loss: 1.6965... Val Loss: 1.6595
Epoch: 2/2... Step: 44210... Loss: 1.4871... Val Loss: 1.6598
Epoch: 2

Epoch: 2/2... Step: 45390... Loss: 1.8482... Val Loss: 1.6543
Epoch: 2/2... Step: 45400... Loss: 2.1441... Val Loss: 1.6501
Epoch: 2/2... Step: 45410... Loss: 1.8033... Val Loss: 1.6503
Epoch: 2/2... Step: 45420... Loss: 1.8193... Val Loss: 1.6498
Epoch: 2/2... Step: 45430... Loss: 2.1767... Val Loss: 1.6511
Epoch: 2/2... Step: 45440... Loss: 1.8995... Val Loss: 1.6538
Epoch: 2/2... Step: 45450... Loss: 1.5046... Val Loss: 1.6551
Epoch: 2/2... Step: 45460... Loss: 1.8578... Val Loss: 1.6533
Epoch: 2/2... Step: 45470... Loss: 1.9393... Val Loss: 1.6528
Epoch: 2/2... Step: 45480... Loss: 1.4460... Val Loss: 1.6539
Epoch: 2/2... Step: 45490... Loss: 1.4937... Val Loss: 1.6527
Epoch: 2/2... Step: 45500... Loss: 1.5396... Val Loss: 1.6513
Epoch: 2/2... Step: 45510... Loss: 1.4086... Val Loss: 1.6497
Epoch: 2/2... Step: 45520... Loss: 1.6673... Val Loss: 1.6501
Epoch: 2/2... Step: 45530... Loss: 1.5634... Val Loss: 1.6502
Epoch: 2/2... Step: 45540... Loss: 1.6234... Val Loss: 1.6501
Epoch: 2

Epoch: 2/2... Step: 46720... Loss: 1.8576... Val Loss: 1.6470
Epoch: 2/2... Step: 46730... Loss: 2.2058... Val Loss: 1.6471
Epoch: 2/2... Step: 46740... Loss: 1.4694... Val Loss: 1.6477
Epoch: 2/2... Step: 46750... Loss: 1.4336... Val Loss: 1.6484
Epoch: 2/2... Step: 46760... Loss: 1.4766... Val Loss: 1.6451
Epoch: 2/2... Step: 46770... Loss: 1.8024... Val Loss: 1.6425
Epoch: 2/2... Step: 46780... Loss: 1.5099... Val Loss: 1.6433
Epoch: 2/2... Step: 46790... Loss: 1.6935... Val Loss: 1.6453
Epoch: 2/2... Step: 46800... Loss: 1.3894... Val Loss: 1.6464
Epoch: 2/2... Step: 46810... Loss: 1.7103... Val Loss: 1.6465
Epoch: 2/2... Step: 46820... Loss: 1.7901... Val Loss: 1.6481
Epoch: 2/2... Step: 46830... Loss: 1.6164... Val Loss: 1.6500
Epoch: 2/2... Step: 46840... Loss: 1.5938... Val Loss: 1.6501
Epoch: 2/2... Step: 46850... Loss: 1.6859... Val Loss: 1.6504
Epoch: 2/2... Step: 46860... Loss: 1.6044... Val Loss: 1.6484
Epoch: 2/2... Step: 46870... Loss: 1.7219... Val Loss: 1.6485
Epoch: 2

Epoch: 2/2... Step: 48050... Loss: 1.7281... Val Loss: 1.6483
Epoch: 2/2... Step: 48060... Loss: 1.5488... Val Loss: 1.6478
Epoch: 2/2... Step: 48070... Loss: 2.0430... Val Loss: 1.6483
Epoch: 2/2... Step: 48080... Loss: 2.0955... Val Loss: 1.6472
Epoch: 2/2... Step: 48090... Loss: 1.6945... Val Loss: 1.6464
Epoch: 2/2... Step: 48100... Loss: 1.3870... Val Loss: 1.6480
Epoch: 2/2... Step: 48110... Loss: 2.0284... Val Loss: 1.6509
Epoch: 2/2... Step: 48120... Loss: 1.5293... Val Loss: 1.6500
Epoch: 2/2... Step: 48130... Loss: 1.6518... Val Loss: 1.6482
Epoch: 2/2... Step: 48140... Loss: 1.9237... Val Loss: 1.6491
Epoch: 2/2... Step: 48150... Loss: 1.9834... Val Loss: 1.6499
Epoch: 2/2... Step: 48160... Loss: 1.3237... Val Loss: 1.6512
Epoch: 2/2... Step: 48170... Loss: 1.2525... Val Loss: 1.6503
Epoch: 2/2... Step: 48180... Loss: 1.8668... Val Loss: 1.6515
Epoch: 2/2... Step: 48190... Loss: 1.6577... Val Loss: 1.6524
Epoch: 2/2... Step: 48200... Loss: 2.1431... Val Loss: 1.6529
Epoch: 2

Epoch: 2/2... Step: 49380... Loss: 1.9244... Val Loss: 1.6453
Epoch: 2/2... Step: 49390... Loss: 1.7490... Val Loss: 1.6442
Epoch: 2/2... Step: 49400... Loss: 1.6745... Val Loss: 1.6436
Epoch: 2/2... Step: 49410... Loss: 1.7392... Val Loss: 1.6421
Epoch: 2/2... Step: 49420... Loss: 1.7399... Val Loss: 1.6413
Epoch: 2/2... Step: 49430... Loss: 1.4469... Val Loss: 1.6420
Epoch: 2/2... Step: 49440... Loss: 2.0715... Val Loss: 1.6421
Epoch: 2/2... Step: 49450... Loss: 1.5099... Val Loss: 1.6415
Epoch: 2/2... Step: 49460... Loss: 1.3723... Val Loss: 1.6424
Epoch: 2/2... Step: 49470... Loss: 1.4912... Val Loss: 1.6440
Epoch: 2/2... Step: 49480... Loss: 1.7267... Val Loss: 1.6451
Epoch: 2/2... Step: 49490... Loss: 1.9213... Val Loss: 1.6479
Epoch: 2/2... Step: 49500... Loss: 1.7057... Val Loss: 1.6476
Epoch: 2/2... Step: 49510... Loss: 1.5223... Val Loss: 1.6476
Epoch: 2/2... Step: 49520... Loss: 1.4039... Val Loss: 1.6465
Epoch: 2/2... Step: 49530... Loss: 1.6501... Val Loss: 1.6451
Epoch: 2

Epoch: 2/2... Step: 50710... Loss: 1.6759... Val Loss: 1.6390
Epoch: 2/2... Step: 50720... Loss: 1.5093... Val Loss: 1.6394
Epoch: 2/2... Step: 50730... Loss: 1.3611... Val Loss: 1.6405
Epoch: 2/2... Step: 50740... Loss: 2.2726... Val Loss: 1.6434
Epoch: 2/2... Step: 50750... Loss: 1.4784... Val Loss: 1.6459
Epoch: 2/2... Step: 50760... Loss: 1.4812... Val Loss: 1.6451
Epoch: 2/2... Step: 50770... Loss: 1.6387... Val Loss: 1.6434
Epoch: 2/2... Step: 50780... Loss: 1.4147... Val Loss: 1.6419
Epoch: 2/2... Step: 50790... Loss: 1.4350... Val Loss: 1.6414
Epoch: 2/2... Step: 50800... Loss: 1.4913... Val Loss: 1.6415
Epoch: 2/2... Step: 50810... Loss: 1.5623... Val Loss: 1.6382
Epoch: 2/2... Step: 50820... Loss: 1.1900... Val Loss: 1.6369
Epoch: 2/2... Step: 50830... Loss: 1.5294... Val Loss: 1.6382
Epoch: 2/2... Step: 50840... Loss: 2.0079... Val Loss: 1.6399
Epoch: 2/2... Step: 50850... Loss: 1.6920... Val Loss: 1.6399
Epoch: 2/2... Step: 50860... Loss: 1.6306... Val Loss: 1.6394
Epoch: 2

Epoch: 2/2... Step: 52040... Loss: 1.7202... Val Loss: 1.6279
Epoch: 2/2... Step: 52050... Loss: 1.3477... Val Loss: 1.6289
Epoch: 2/2... Step: 52060... Loss: 1.6214... Val Loss: 1.6292
Epoch: 2/2... Step: 52070... Loss: 1.4349... Val Loss: 1.6303
Epoch: 2/2... Step: 52080... Loss: 1.4925... Val Loss: 1.6296
Epoch: 2/2... Step: 52090... Loss: 1.6913... Val Loss: 1.6285
Epoch: 2/2... Step: 52100... Loss: 1.6724... Val Loss: 1.6283
Epoch: 2/2... Step: 52110... Loss: 1.5304... Val Loss: 1.6280
Epoch: 2/2... Step: 52120... Loss: 1.7522... Val Loss: 1.6284
Epoch: 2/2... Step: 52130... Loss: 1.9018... Val Loss: 1.6284
Epoch: 2/2... Step: 52140... Loss: 1.3351... Val Loss: 1.6292
Epoch: 2/2... Step: 52150... Loss: 1.4375... Val Loss: 1.6306
Epoch: 2/2... Step: 52160... Loss: 1.8316... Val Loss: 1.6330
Epoch: 2/2... Step: 52170... Loss: 1.8687... Val Loss: 1.6328
Epoch: 2/2... Step: 52180... Loss: 1.7868... Val Loss: 1.6337
Epoch: 2/2... Step: 52190... Loss: 1.5147... Val Loss: 1.6361
Epoch: 2

Epoch: 2/2... Step: 53370... Loss: 1.3639... Val Loss: 1.6310
Epoch: 2/2... Step: 53380... Loss: 1.8725... Val Loss: 1.6317
Epoch: 2/2... Step: 53390... Loss: 1.9509... Val Loss: 1.6321
Epoch: 2/2... Step: 53400... Loss: 1.7121... Val Loss: 1.6309
Epoch: 2/2... Step: 53410... Loss: 1.5552... Val Loss: 1.6315
Epoch: 2/2... Step: 53420... Loss: 2.1206... Val Loss: 1.6313
Epoch: 2/2... Step: 53430... Loss: 1.9585... Val Loss: 1.6317
Epoch: 2/2... Step: 53440... Loss: 1.6065... Val Loss: 1.6324
Epoch: 2/2... Step: 53450... Loss: 1.3721... Val Loss: 1.6330
Epoch: 2/2... Step: 53460... Loss: 1.8577... Val Loss: 1.6344
Epoch: 2/2... Step: 53470... Loss: 1.4566... Val Loss: 1.6320
Epoch: 2/2... Step: 53480... Loss: 1.7079... Val Loss: 1.6308
Epoch: 2/2... Step: 53490... Loss: 1.6655... Val Loss: 1.6305
Epoch: 2/2... Step: 53500... Loss: 1.4407... Val Loss: 1.6310
Epoch: 2/2... Step: 53510... Loss: 1.9563... Val Loss: 1.6320
Epoch: 2/2... Step: 53520... Loss: 1.6230... Val Loss: 1.6332
Epoch: 2

Epoch: 2/2... Step: 54700... Loss: 1.6661... Val Loss: 1.6287
Epoch: 2/2... Step: 54710... Loss: 1.4849... Val Loss: 1.6294
Epoch: 2/2... Step: 54720... Loss: 1.1546... Val Loss: 1.6298
Epoch: 2/2... Step: 54730... Loss: 1.5409... Val Loss: 1.6283
Epoch: 2/2... Step: 54740... Loss: 1.2543... Val Loss: 1.6271
Epoch: 2/2... Step: 54750... Loss: 1.4116... Val Loss: 1.6267
Epoch: 2/2... Step: 54760... Loss: 1.6932... Val Loss: 1.6287
Epoch: 2/2... Step: 54770... Loss: 1.5177... Val Loss: 1.6309
Epoch: 2/2... Step: 54780... Loss: 1.7127... Val Loss: 1.6327
Epoch: 2/2... Step: 54790... Loss: 1.7002... Val Loss: 1.6295
Epoch: 2/2... Step: 54800... Loss: 1.5820... Val Loss: 1.6270
Epoch: 2/2... Step: 54810... Loss: 1.4201... Val Loss: 1.6282
Epoch: 2/2... Step: 54820... Loss: 1.7449... Val Loss: 1.6285
Epoch: 2/2... Step: 54830... Loss: 1.2788... Val Loss: 1.6274
Epoch: 2/2... Step: 54840... Loss: 1.2173... Val Loss: 1.6268
Epoch: 2/2... Step: 54850... Loss: 1.6556... Val Loss: 1.6274
Epoch: 2

Epoch: 2/2... Step: 56030... Loss: 1.7276... Val Loss: 1.6286
Epoch: 2/2... Step: 56040... Loss: 1.7160... Val Loss: 1.6296
Epoch: 2/2... Step: 56050... Loss: 1.7181... Val Loss: 1.6305
Epoch: 2/2... Step: 56060... Loss: 1.6087... Val Loss: 1.6291
Epoch: 2/2... Step: 56070... Loss: 1.7272... Val Loss: 1.6272
Epoch: 2/2... Step: 56080... Loss: 1.6422... Val Loss: 1.6268
Epoch: 2/2... Step: 56090... Loss: 1.8016... Val Loss: 1.6272
Epoch: 2/2... Step: 56100... Loss: 1.5587... Val Loss: 1.6270
Epoch: 2/2... Step: 56110... Loss: 1.9219... Val Loss: 1.6274
Epoch: 2/2... Step: 56120... Loss: 1.5022... Val Loss: 1.6271
Epoch: 2/2... Step: 56130... Loss: 1.9230... Val Loss: 1.6299
Epoch: 2/2... Step: 56140... Loss: 1.6850... Val Loss: 1.6312
Epoch: 2/2... Step: 56150... Loss: 2.3061... Val Loss: 1.6310
Epoch: 2/2... Step: 56160... Loss: 1.6411... Val Loss: 1.6299
Epoch: 2/2... Step: 56170... Loss: 1.7326... Val Loss: 1.6293
Epoch: 2/2... Step: 56180... Loss: 1.5527... Val Loss: 1.6288
Epoch: 2

Epoch: 2/2... Step: 57360... Loss: 1.5122... Val Loss: 1.6161
Epoch: 2/2... Step: 57370... Loss: 1.7988... Val Loss: 1.6165
Epoch: 2/2... Step: 57380... Loss: 1.7132... Val Loss: 1.6175
Epoch: 2/2... Step: 57390... Loss: 1.4609... Val Loss: 1.6182
Epoch: 2/2... Step: 57400... Loss: 1.8945... Val Loss: 1.6185
Epoch: 2/2... Step: 57410... Loss: 2.0404... Val Loss: 1.6185
Epoch: 2/2... Step: 57420... Loss: 1.7262... Val Loss: 1.6188
Epoch: 2/2... Step: 57430... Loss: 1.5558... Val Loss: 1.6223
Epoch: 2/2... Step: 57440... Loss: 2.1499... Val Loss: 1.6226
Epoch: 2/2... Step: 57450... Loss: 1.3368... Val Loss: 1.6201
Epoch: 2/2... Step: 57460... Loss: 1.7644... Val Loss: 1.6201
Epoch: 2/2... Step: 57470... Loss: 1.6664... Val Loss: 1.6189
Epoch: 2/2... Step: 57480... Loss: 1.5167... Val Loss: 1.6193
Epoch: 2/2... Step: 57490... Loss: 1.5349... Val Loss: 1.6209
Epoch: 2/2... Step: 57500... Loss: 1.2790... Val Loss: 1.6215
Epoch: 2/2... Step: 57510... Loss: 1.5630... Val Loss: 1.6203
Epoch: 2

Epoch: 2/2... Step: 58690... Loss: 1.7258... Val Loss: 1.6168
Epoch: 2/2... Step: 58700... Loss: 2.2163... Val Loss: 1.6173
Epoch: 2/2... Step: 58710... Loss: 2.2324... Val Loss: 1.6181
Epoch: 2/2... Step: 58720... Loss: 1.7309... Val Loss: 1.6190
Epoch: 2/2... Step: 58730... Loss: 1.2933... Val Loss: 1.6186
Epoch: 2/2... Step: 58740... Loss: 1.6560... Val Loss: 1.6180
Epoch: 2/2... Step: 58750... Loss: 1.3966... Val Loss: 1.6165
Epoch: 2/2... Step: 58760... Loss: 1.6588... Val Loss: 1.6171
Epoch: 2/2... Step: 58770... Loss: 1.9613... Val Loss: 1.6163
Epoch: 2/2... Step: 58780... Loss: 1.9478... Val Loss: 1.6145
Epoch: 2/2... Step: 58790... Loss: 1.4184... Val Loss: 1.6149
Epoch: 2/2... Step: 58800... Loss: 1.6453... Val Loss: 1.6152
Epoch: 2/2... Step: 58810... Loss: 1.8141... Val Loss: 1.6168
Epoch: 2/2... Step: 58820... Loss: 1.8587... Val Loss: 1.6193
Epoch: 2/2... Step: 58830... Loss: 1.7589... Val Loss: 1.6186
Epoch: 2/2... Step: 58840... Loss: 1.7901... Val Loss: 1.6181
Epoch: 2

Epoch: 2/2... Step: 60020... Loss: 1.2689... Val Loss: 1.6172
Epoch: 2/2... Step: 60030... Loss: 1.8506... Val Loss: 1.6179
Epoch: 2/2... Step: 60040... Loss: 1.7443... Val Loss: 1.6186
Epoch: 2/2... Step: 60050... Loss: 1.4991... Val Loss: 1.6185
Epoch: 2/2... Step: 60060... Loss: 1.5874... Val Loss: 1.6187
Epoch: 2/2... Step: 60070... Loss: 1.4902... Val Loss: 1.6175
Epoch: 2/2... Step: 60080... Loss: 1.5857... Val Loss: 1.6177
Epoch: 2/2... Step: 60090... Loss: 1.8424... Val Loss: 1.6183
Epoch: 2/2... Step: 60100... Loss: 1.6358... Val Loss: 1.6190
Epoch: 2/2... Step: 60110... Loss: 1.7551... Val Loss: 1.6194
Epoch: 2/2... Step: 60120... Loss: 1.6543... Val Loss: 1.6197
Epoch: 2/2... Step: 60130... Loss: 1.4467... Val Loss: 1.6165
Epoch: 2/2... Step: 60140... Loss: 1.6338... Val Loss: 1.6157
Epoch: 2/2... Step: 60150... Loss: 1.7277... Val Loss: 1.6150
Epoch: 2/2... Step: 60160... Loss: 1.6027... Val Loss: 1.6148
Epoch: 2/2... Step: 60170... Loss: 1.6479... Val Loss: 1.6141
Epoch: 2

Epoch: 2/2... Step: 61350... Loss: 2.0134... Val Loss: 1.6154
Epoch: 2/2... Step: 61360... Loss: 1.3480... Val Loss: 1.6132
Epoch: 2/2... Step: 61370... Loss: 1.5432... Val Loss: 1.6125
Epoch: 2/2... Step: 61380... Loss: 1.4244... Val Loss: 1.6125
Epoch: 2/2... Step: 61390... Loss: 1.6719... Val Loss: 1.6126
Epoch: 2/2... Step: 61400... Loss: 1.2535... Val Loss: 1.6145
Epoch: 2/2... Step: 61410... Loss: 1.5452... Val Loss: 1.6160
Epoch: 2/2... Step: 61420... Loss: 1.6701... Val Loss: 1.6151
Epoch: 2/2... Step: 61430... Loss: 1.4724... Val Loss: 1.6148
Epoch: 2/2... Step: 61440... Loss: 1.6607... Val Loss: 1.6137
Epoch: 2/2... Step: 61450... Loss: 1.9645... Val Loss: 1.6115
Epoch: 2/2... Step: 61460... Loss: 1.7055... Val Loss: 1.6086
Epoch: 2/2... Step: 61470... Loss: 2.0648... Val Loss: 1.6085
Epoch: 2/2... Step: 61480... Loss: 1.4762... Val Loss: 1.6088
Epoch: 2/2... Step: 61490... Loss: 1.5690... Val Loss: 1.6082
Epoch: 2/2... Step: 61500... Loss: 1.8478... Val Loss: 1.6087
Epoch: 2

Epoch: 2/2... Step: 62680... Loss: 1.1194... Val Loss: 1.6177
Epoch: 2/2... Step: 62690... Loss: 1.5197... Val Loss: 1.6180
Epoch: 2/2... Step: 62700... Loss: 1.6171... Val Loss: 1.6152
Epoch: 2/2... Step: 62710... Loss: 1.6506... Val Loss: 1.6145
Epoch: 2/2... Step: 62720... Loss: 1.5788... Val Loss: 1.6155
Epoch: 2/2... Step: 62730... Loss: 1.8224... Val Loss: 1.6161
Epoch: 2/2... Step: 62740... Loss: 1.8065... Val Loss: 1.6158
Epoch: 2/2... Step: 62750... Loss: 1.5867... Val Loss: 1.6150
Epoch: 2/2... Step: 62760... Loss: 1.7495... Val Loss: 1.6140
Epoch: 2/2... Step: 62770... Loss: 2.0081... Val Loss: 1.6124
Epoch: 2/2... Step: 62780... Loss: 2.2499... Val Loss: 1.6115
Epoch: 2/2... Step: 62790... Loss: 1.8668... Val Loss: 1.6103
Epoch: 2/2... Step: 62800... Loss: 1.7573... Val Loss: 1.6089
Epoch: 2/2... Step: 62810... Loss: 1.3630... Val Loss: 1.6089
Epoch: 2/2... Step: 62820... Loss: 1.6033... Val Loss: 1.6099
Epoch: 2/2... Step: 62830... Loss: 1.8967... Val Loss: 1.6107
Epoch: 2

Epoch: 2/2... Step: 64010... Loss: 1.7658... Val Loss: 1.6133
Epoch: 2/2... Step: 64020... Loss: 1.6498... Val Loss: 1.6131
Epoch: 2/2... Step: 64030... Loss: 1.8278... Val Loss: 1.6136
Epoch: 2/2... Step: 64040... Loss: 1.9064... Val Loss: 1.6128
Epoch: 2/2... Step: 64050... Loss: 1.8412... Val Loss: 1.6097
Epoch: 2/2... Step: 64060... Loss: 1.7703... Val Loss: 1.6085
Epoch: 2/2... Step: 64070... Loss: 1.8171... Val Loss: 1.6097
Epoch: 2/2... Step: 64080... Loss: 1.6113... Val Loss: 1.6104
Epoch: 2/2... Step: 64090... Loss: 1.4375... Val Loss: 1.6117
Epoch: 2/2... Step: 64100... Loss: 1.5673... Val Loss: 1.6131
Epoch: 2/2... Step: 64110... Loss: 1.6053... Val Loss: 1.6140
Epoch: 2/2... Step: 64120... Loss: 1.5893... Val Loss: 1.6131
Epoch: 2/2... Step: 64130... Loss: 1.8144... Val Loss: 1.6126
Epoch: 2/2... Step: 64140... Loss: 1.0572... Val Loss: 1.6114
Epoch: 2/2... Step: 64150... Loss: 2.0611... Val Loss: 1.6127
Epoch: 2/2... Step: 64160... Loss: 1.4356... Val Loss: 1.6126
Epoch: 2

Epoch: 2/2... Step: 65340... Loss: 1.5574... Val Loss: 1.6173
Epoch: 2/2... Step: 65350... Loss: 2.0731... Val Loss: 1.6157
Epoch: 2/2... Step: 65360... Loss: 1.6107... Val Loss: 1.6151
Epoch: 2/2... Step: 65370... Loss: 1.7954... Val Loss: 1.6169
Epoch: 2/2... Step: 65380... Loss: 1.7583... Val Loss: 1.6161
Epoch: 2/2... Step: 65390... Loss: 1.7131... Val Loss: 1.6159
Epoch: 2/2... Step: 65400... Loss: 1.1417... Val Loss: 1.6171
Epoch: 2/2... Step: 65410... Loss: 1.8420... Val Loss: 1.6203
Epoch: 2/2... Step: 65420... Loss: 1.5976... Val Loss: 1.6193
Epoch: 2/2... Step: 65430... Loss: 1.4030... Val Loss: 1.6186
Epoch: 2/2... Step: 65440... Loss: 1.5487... Val Loss: 1.6176
Epoch: 2/2... Step: 65450... Loss: 1.2318... Val Loss: 1.6174
Epoch: 2/2... Step: 65460... Loss: 1.3608... Val Loss: 1.6180
Epoch: 2/2... Step: 65470... Loss: 1.6528... Val Loss: 1.6152
Epoch: 2/2... Step: 65480... Loss: 1.4431... Val Loss: 1.6174
Epoch: 2/2... Step: 65490... Loss: 1.6620... Val Loss: 1.6193
Epoch: 2

Epoch: 2/2... Step: 66670... Loss: 1.4237... Val Loss: 1.6132
Epoch: 2/2... Step: 66680... Loss: 1.9386... Val Loss: 1.6146
Epoch: 2/2... Step: 66690... Loss: 1.5249... Val Loss: 1.6149
Epoch: 2/2... Step: 66700... Loss: 1.5856... Val Loss: 1.6142
Epoch: 2/2... Step: 66710... Loss: 1.8937... Val Loss: 1.6129
Epoch: 2/2... Step: 66720... Loss: 2.3357... Val Loss: 1.6117
Epoch: 2/2... Step: 66730... Loss: 1.5534... Val Loss: 1.6125
Epoch: 2/2... Step: 66740... Loss: 1.4937... Val Loss: 1.6141
Epoch: 2/2... Step: 66750... Loss: 1.3124... Val Loss: 1.6146
Epoch: 2/2... Step: 66760... Loss: 1.3180... Val Loss: 1.6137
Epoch: 2/2... Step: 66770... Loss: 1.7404... Val Loss: 1.6126
Epoch: 2/2... Step: 66780... Loss: 1.5402... Val Loss: 1.6133
Epoch: 2/2... Step: 66790... Loss: 1.4547... Val Loss: 1.6134
Epoch: 2/2... Step: 66800... Loss: 1.5505... Val Loss: 1.6129
Epoch: 2/2... Step: 66810... Loss: 1.4761... Val Loss: 1.6131
Epoch: 2/2... Step: 66820... Loss: 1.9234... Val Loss: 1.6144
Epoch: 2

Epoch: 2/2... Step: 68000... Loss: 2.2173... Val Loss: 1.6063
Epoch: 2/2... Step: 68010... Loss: 1.7289... Val Loss: 1.6072
Epoch: 2/2... Step: 68020... Loss: 1.6163... Val Loss: 1.6071
Epoch: 2/2... Step: 68030... Loss: 1.5386... Val Loss: 1.6085
Epoch: 2/2... Step: 68040... Loss: 1.4138... Val Loss: 1.6099
Epoch: 2/2... Step: 68050... Loss: 1.5523... Val Loss: 1.6106
Epoch: 2/2... Step: 68060... Loss: 1.8093... Val Loss: 1.6113
Epoch: 2/2... Step: 68070... Loss: 1.4294... Val Loss: 1.6119
Epoch: 2/2... Step: 68080... Loss: 1.5948... Val Loss: 1.6108
Epoch: 2/2... Step: 68090... Loss: 1.8013... Val Loss: 1.6089
Epoch: 2/2... Step: 68100... Loss: 2.0321... Val Loss: 1.6094
Epoch: 2/2... Step: 68110... Loss: 1.6896... Val Loss: 1.6111
Epoch: 2/2... Step: 68120... Loss: 1.6897... Val Loss: 1.6115
Epoch: 2/2... Step: 68130... Loss: 1.7393... Val Loss: 1.6122
Epoch: 2/2... Step: 68140... Loss: 1.9218... Val Loss: 1.6124
Epoch: 2/2... Step: 68150... Loss: 1.5346... Val Loss: 1.6125
Epoch: 2

Epoch: 2/2... Step: 69330... Loss: 1.9810... Val Loss: 1.6127
Epoch: 2/2... Step: 69340... Loss: 1.5942... Val Loss: 1.6091
Epoch: 2/2... Step: 69350... Loss: 0.9921... Val Loss: 1.6067
Epoch: 2/2... Step: 69360... Loss: 1.7910... Val Loss: 1.6065
Epoch: 2/2... Step: 69370... Loss: 1.5096... Val Loss: 1.6090
Epoch: 2/2... Step: 69380... Loss: 1.4734... Val Loss: 1.6114
Epoch: 2/2... Step: 69390... Loss: 1.6577... Val Loss: 1.6114
Epoch: 2/2... Step: 69400... Loss: 1.7670... Val Loss: 1.6130
Epoch: 2/2... Step: 69410... Loss: 1.2264... Val Loss: 1.6109
Epoch: 2/2... Step: 69420... Loss: 1.5825... Val Loss: 1.6084
Epoch: 2/2... Step: 69430... Loss: 1.4385... Val Loss: 1.6073
Epoch: 2/2... Step: 69440... Loss: 1.1475... Val Loss: 1.6064
Epoch: 2/2... Step: 69450... Loss: 1.6039... Val Loss: 1.6072
Epoch: 2/2... Step: 69460... Loss: 1.6837... Val Loss: 1.6068
Epoch: 2/2... Step: 69470... Loss: 2.2292... Val Loss: 1.6048
Epoch: 2/2... Step: 69480... Loss: 1.9781... Val Loss: 1.6024
Epoch: 2

Epoch: 2/2... Step: 70660... Loss: 1.3725... Val Loss: 1.5980
Epoch: 2/2... Step: 70670... Loss: 1.5075... Val Loss: 1.5966
Epoch: 2/2... Step: 70680... Loss: 1.2475... Val Loss: 1.5972
Epoch: 2/2... Step: 70690... Loss: 1.5613... Val Loss: 1.5976
Epoch: 2/2... Step: 70700... Loss: 1.3995... Val Loss: 1.5981
Epoch: 2/2... Step: 70710... Loss: 2.2824... Val Loss: 1.5981
Epoch: 2/2... Step: 70720... Loss: 1.4317... Val Loss: 1.5989
Epoch: 2/2... Step: 70730... Loss: 1.5497... Val Loss: 1.5996
Epoch: 2/2... Step: 70740... Loss: 1.5057... Val Loss: 1.5999
Epoch: 2/2... Step: 70750... Loss: 2.3400... Val Loss: 1.6004
Epoch: 2/2... Step: 70760... Loss: 2.0130... Val Loss: 1.6017
Epoch: 2/2... Step: 70770... Loss: 1.4667... Val Loss: 1.6021
Epoch: 2/2... Step: 70780... Loss: 1.5041... Val Loss: 1.6021
Epoch: 2/2... Step: 70790... Loss: 1.7912... Val Loss: 1.6020
Epoch: 2/2... Step: 70800... Loss: 1.5410... Val Loss: 1.6005
Epoch: 2/2... Step: 70810... Loss: 1.6802... Val Loss: 1.5981
Epoch: 2

## Getting the best model

To set your hyperparameters to get the best performance, you'll want to watch the training and validation losses. If your training loss is much lower than the validation loss, you're overfitting. Increase regularization (more dropout) or use a smaller network. If the training and validation losses are close, you're underfitting so you can increase the size of the network.

## Hyperparameters

Here are the hyperparameters for the network.

In defining the model:
* `n_hidden` - The number of units in the hidden layers.
* `n_layers` - Number of hidden LSTM layers to use.

We assume that dropout probability and learning rate will be kept at the default, in this example.

And in training:
* `batch_size` - Number of sequences running through the network in one pass.
* `seq_length` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lr` - Learning rate for training

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `n_hidden` and `n_layers`. I would advise that you always use `n_layers` of either 2/3. The `n_hidden` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `n_hidden` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.

## Checkpoint

After training, we'll save the model so we can load it again later if we need too. Here I'm saving the parameters needed to create the same architecture, the hidden layer hyperparameters and the text characters.

In [161]:
# change the name, for saving multiple files
model_name = 'rnn_2_epoch.net'

checkpoint = {'n_hidden': net.n_hidden,
              'n_layers': net.n_layers,
              'state_dict': net.state_dict(),
              'tokens': net.chars}

with open(model_name, 'wb') as f:
    torch.save(checkpoint, f)

---
## Making Predictions

Now that the model is trained, we'll want to sample from it and make predictions about next characters! To sample, we pass in a character and have the network predict the next character. Then we take that character, pass it back in, and get another predicted character. Just keep doing this and you'll generate a bunch of text!

### A note on the `predict`  function

The output of our RNN is from a fully-connected layer and it outputs a **distribution of next-character scores**.

> To actually get the next character, we apply a softmax function, which gives us a *probability* distribution that we can then sample to predict the next character.

### Top K sampling

Our predictions come from a categorical probability distribution over all the possible characters. We can make the sample text and make it more reasonable to handle (with less variables) by only considering some $K$ most probable characters. This will prevent the network from giving us completely absurd characters while allowing it to introduce some noise and randomness into the sampled text. Read more about [topk, here](https://pytorch.org/docs/stable/torch.html#torch.topk).


In [162]:
def predict(net, char, h=None, top_k=None):
        ''' Given a character, predict the next character.
            Returns the predicted character and the hidden state.
        '''
        
        # tensor inputs
        x = np.array([[net.char2int[char]]])
        x = one_hot_encode(x, len(net.chars))
        inputs = torch.from_numpy(x)
        
        if(train_on_gpu):
            inputs = inputs.cuda()
        
        # detach hidden state from history
        h = tuple([each.data for each in h])
        # get the output of the model
        out, h = net(inputs, h)

        # get the character probabilities
        p = F.softmax(out, dim=1).data
        if(train_on_gpu):
            p = p.cpu() # move to cpu
        
        # get top characters
        if top_k is None:
            top_ch = np.arange(len(net.chars))
        else:
            p, top_ch = p.topk(top_k)
            top_ch = top_ch.numpy().squeeze()
        
        # select the likely next character with some element of randomness
        p = p.numpy().squeeze()
        char = np.random.choice(top_ch, p=p/p.sum())
        
        # return the encoded value of the predicted char and the hidden state
        return net.int2char[char], h

### Priming and generating text 

Typically you'll want to prime the network so you can build up a hidden state. Otherwise the network will start out generating characters at random. In general the first bunch of characters will be a little rough since it hasn't built up a long history of characters to predict from.

In [163]:
def sample(net, size, prime='The', top_k=None):
        
    if(train_on_gpu):
        net.cuda()
    else:
        net.cpu()
    
    net.eval() # eval mode
    
    # First off, run through the prime characters
    chars = [ch for ch in prime]
    h = net.init_hidden(1)
    for ch in prime:
        char, h = predict(net, ch, h, top_k=top_k)

    chars.append(char)
    
    # Now pass in the previous character and get a new one
    for ii in range(size):
        char, h = predict(net, chars[-1], h, top_k=top_k)
        chars.append(char)

    return ''.join(chars)

In [164]:
print(sample(net, 1000, prime='Anna', top_k=5))

Anna, her.

"Who had seemed the shand of her head to thinks to have his frate that the consecarial of a shooting and the dor of the decilition," said
Alexey Alexandrovitch's, and standed the state, but
his cricked,
which his countess and all her streed the did be staying and strat as the semence, and
any the conscion."

There was all so tree. She considersky that so high the
carriage and word," he said of her
three
step of the master and all and so so thought of her thought
and said.

"What's to her will not her whele that the sone, all without that
how the canders, has seemed in the soul and the possation. And she was to her and with the
more had been tooth, and thing in his condistion. "What's note himself to see it and was no to see the porers.

Stepan Arkadyevitch was not
her to her and
the man anyway of this toon, but that she had nettor in
the sand, that. "If I was
to see that
went all the shoot, and the strild a sersing a tood hand. Stepan Arkadyevitch and a most that he would n

## Loading a checkpoint

In [166]:
# Here we have loaded in a model that trained over 20 epochs `rnn_20_epoch.net`
with open('rnn_2_epoch.net', 'rb') as f:
    checkpoint = torch.load(f)
    
loaded = CharRNN(checkpoint['tokens'], n_hidden=checkpoint['n_hidden'], n_layers=checkpoint['n_layers'])
loaded.load_state_dict(checkpoint['state_dict'])

<All keys matched successfully>

In [167]:
# Sample using a loaded model
print(sample(loaded, 2000, top_k=5, prime="And Levin said"))

And Levin said to
all so shat of
share and at the mithrestioned. There was all a mer and had
sone of
her and with a tinganter word of the sore trates of to she
want, that he said into her time of his stroighten who had sore with her has before if.

"The same whor the same. "I have
to be tomother the child had at the sheep at. "It was as a carriage, but she was a completeness at his sayed as
all
had that thought it was not a compreaches
was a master. And will consereres had to still had hind she saw that to him of the door..." She had have the son, that," said Levin's with she
was to be
shot as he was so hand of the same
hollessifily all his
forgienct hand. "You came annor had she
forgoing the proforsiof he had be shating. Alexey Alexandrovitch, a decined.

"I have some, and thoushed at her had had she feel to the mear to this
sered
to this settling, and this were, he went to her
head and as he say
stroing at the still as imparted that she said. "I am not the marre, when he was the
drac